const MATERIALS = {
    reinforced_concrete: {
        id: "reinforced_concrete",
        label: "Железобетон",
        density_kg_m3: 2500,
        heatCapacity_kJ_kgK: 0.84,
        conductivityDry_W_mK: 1.69,
        conductivityA_W_mK: 1.92,
        conductivityB_W_mK: 2.04,
        heatAbsorptionA_W_m2K: 17.98,
        heatAbsorptionB_W_m2K: 18.95,
        vaporPermeability_mg_mhPa: 0.03,
    },
    heavy_concrete: {
        id: "heavy_concrete",
        label: "Тяжелый бетон на гравии или щебне",
        density_kg_m3: 2400,
        heatCapacity_kJ_kgK: 0.84,
        conductivityDry_W_mK: 1.51,
        conductivityA_W_mK: 1.74,
        conductivityB_W_mK: 1.86,
        heatAbsorptionA_W_m2K: 16.77,
        heatAbsorptionB_W_m2K: 17.88,
        vaporPermeability_mg_mhPa: 0.03,
    },
    expanded_clay_concrete: {
        id: "expanded_clay_concrete",
        label: "Керамзитобетон на кварцевом песке",
        density_kg_m3: 1000,
        heatCapacity_kJ_kgK: 0.84,
        conductivityDry_W_mK: 0.33,
        conductivityA_W_mK: 0.41,
        conductivityB_W_mK: 0.47,
        heatAbsorptionA_W_m2K: 5.49,
        heatAbsorptionB_W_m2K: 6.35,
        vaporPermeability_mg_mhPa: 0.075,
    },
    ceramic_brick: {
        id: "ceramic_brick",
        label: "Кирпич керамический пустотный на цементно-песчаном растворе",
        density_kg_m3: 1400,
        heatCapacity_kJ_kgK: 0.88,
        conductivityDry_W_mK: 0.41,
        conductivityA_W_mK: 0.52,
        conductivityB_W_mK: 0.58,
        heatAbsorptionA_W_m2K: 7.01,
        heatAbsorptionB_W_m2K: 7.56,
        vaporPermeability_mg_mhPa: 0.16,
    },
    silicate_brick: {
        id: "silicate_brick",
        label: "Кирпич силикатный на цементно-песчаном растворе",
        density_kg_m3: 1800,
        heatCapacity_kJ_kgK: 0.88,
        conductivityDry_W_mK: 0.7,
        conductivityA_W_mK: 0.76,
        conductivityB_W_mK: 0.87,
        heatAbsorptionA_W_m2K: 9.77,
        heatAbsorptionB_W_m2K: 10.9,
        vaporPermeability_mg_mhPa: 0.11,
    },
    aerated_concrete: {
        id: "aerated_concrete",
        label: "Ячеистый бетон / газобетон",
        density_kg_m3: 500,
        heatCapacity_kJ_kgK: 0.84,
        conductivityDry_W_mK: 0.14,
        conductivityA_W_mK: 0.17,
        conductivityB_W_mK: 0.23,
        heatAbsorptionA_W_m2K: 2.55,
        heatAbsorptionB_W_m2K: 3.25,
        vaporPermeability_mg_mhPa: 0.3,
        isApproximate: true,
        sourceNote: "Рабочая аппроксимация для демонстрации по плотности 500 кг/м3; при необходимости заменить на точную строку приложения М для выбранной марки газобетона.",
    },
    cement_sand_plaster: {
        id: "cement_sand_plaster",
        label: "Цементно-песчаная штукатурка / раствор",
        density_kg_m3: 1800,
        heatCapacity_kJ_kgK: 0.84,
        conductivityDry_W_mK: 0.58,
        conductivityA_W_mK: 0.76,
        conductivityB_W_mK: 0.93,
        heatAbsorptionA_W_m2K: 9.6,
        heatAbsorptionB_W_m2K: 11.09,
        vaporPermeability_mg_mhPa: 0.09,
    },
    gypsum_plaster: {
        id: "gypsum_plaster",
        label: "Гипсовая штукатурка",
        density_kg_m3: 1050,
        heatCapacity_kJ_kgK: 0.84,
        conductivityDry_W_mK: 0.15,
        conductivityA_W_mK: 0.34,
        conductivityB_W_mK: 0.36,
        heatAbsorptionA_W_m2K: 5.12,
        heatAbsorptionB_W_m2K: 5.48,
        vaporPermeability_mg_mhPa: 0.075,
        isApproximate: true,
        sourceNote: "Для рабочего набора используется строка гипсовых строительных плит / сухой штукатурки как ближайший материал.",
    },
    mineral_wool: {
        id: "mineral_wool",
        label: "Минераловатные плиты",
        density_kg_m3: 35,
        heatCapacity_kJ_kgK: 0.84,
        conductivityDry_W_mK: 0.037,
        conductivityA_W_mK: 0.04,
        conductivityB_W_mK: 0.044,
        heatAbsorptionA_W_m2K: 0.27,
        heatAbsorptionB_W_m2K: 0.29,
        vaporPermeability_mg_mhPa: 0.45,
    },
    eps: {
        id: "eps",
        label: "Пенополистирол",
        density_kg_m3: 25,
        heatCapacity_kJ_kgK: 1.34,
        conductivityDry_W_mK: 0.039,
        conductivityA_W_mK: 0.041,
        conductivityB_W_mK: 0.051,
        heatAbsorptionA_W_m2K: 0.29,
        heatAbsorptionB_W_m2K: 0.32,
        vaporPermeability_mg_mhPa: 0.05,
    },
    xps: {
        id: "xps",
        label: "Экструдированный пенополистирол",
        density_kg_m3: 35,
        heatCapacity_kJ_kgK: 1.5,
        conductivityDry_W_mK: 0.033,
        conductivityA_W_mK: 0.034,
        conductivityB_W_mK: 0.035,
        heatAbsorptionA_W_m2K: 0.33,
        heatAbsorptionB_W_m2K: 0.34,
        vaporPermeability_mg_mhPa: 0.005,
    },
    pur: {
        id: "pur",
        label: "Пенополиуретан",
        density_kg_m3: 60,
        heatCapacity_kJ_kgK: 1.47,
        conductivityDry_W_mK: 0.035,
        conductivityA_W_mK: 0.037,
        conductivityB_W_mK: 0.04,
        heatAbsorptionA_W_m2K: 0.49,
        heatAbsorptionB_W_m2K: 0.55,
        vaporPermeability_mg_mhPa: 0.05,
    },
    wood: {
        id: "wood",
        label: "Древесина хвойных пород",
        density_kg_m3: 500,
        heatCapacity_kJ_kgK: 2.3,
        conductivityDry_W_mK: 0.09,
        conductivityA_W_mK: 0.14,
        conductivityB_W_mK: 0.18,
        heatAbsorptionA_W_m2K: 3.87,
        heatAbsorptionB_W_m2K: 4.54,
        vaporPermeability_mg_mhPa: 0.06,
    },
    plywood: {
        id: "plywood",
        label: "Фанера клееная",
        density_kg_m3: 600,
        heatCapacity_kJ_kgK: 2.3,
        conductivityDry_W_mK: 0.12,
        conductivityA_W_mK: 0.15,
        conductivityB_W_mK: 0.18,
        heatAbsorptionA_W_m2K: 4.22,
        heatAbsorptionB_W_m2K: 4.73,
        vaporPermeability_mg_mhPa: 0.02,
    },
    gypsum_board: {
        id: "gypsum_board",
        label: "Гипсокартон / сухая штукатурка",
        density_kg_m3: 800,
        heatCapacity_kJ_kgK: 0.84,
        conductivityDry_W_mK: 0.15,
        conductivityA_W_mK: 0.19,
        conductivityB_W_mK: 0.21,
        heatAbsorptionA_W_m2K: 3.34,
        heatAbsorptionB_W_m2K: 3.66,
        vaporPermeability_mg_mhPa: 0.075,
    },
    glass: {
        id: "glass",
        label: "Стекло оконное",
        density_kg_m3: 2500,
        heatCapacity_kJ_kgK: 0.84,
        conductivityDry_W_mK: 0.76,
        conductivityA_W_mK: 0.76,
        conductivityB_W_mK: 0.76,
        heatAbsorptionA_W_m2K: 10.79,
        heatAbsorptionB_W_m2K: 10.79,
        vaporPermeability_mg_mhPa: 0,
    },
    window_block: {
        id: "window_block",
        label: "Оконный блок",
        density_kg_m3: 2500,
        heatCapacity_kJ_kgK: 0.84,
        conductivityDry_W_mK: 0.76,
        conductivityA_W_mK: 0.76,
        conductivityB_W_mK: 0.76,
        heatAbsorptionA_W_m2K: 10.79,
        heatAbsorptionB_W_m2K: 10.79,
        vaporPermeability_mg_mhPa: 0,
        isApproximate: true,
        sourceNote: "Для прозрачной части блока используется строка стекла; рамный профиль в послойном расчете не моделируется.",
    },
    pvc_double_glazed_unit_equivalent: {
        id: "pvc_double_glazed_unit_equivalent",
        label: "ПВХ-окно с двухкамерным стеклопакетом (эквивалентный слой)",
        density_kg_m3: 700,
        heatCapacity_kJ_kgK: 0.84,
        conductivityDry_W_mK: 0.065,
        conductivityA_W_mK: 0.07,
        conductivityB_W_mK: 0.075,
        heatAbsorptionA_W_m2K: 2.5,
        heatAbsorptionB_W_m2K: 2.8,
        vaporPermeability_mg_mhPa: 0.02,
        isApproximate: true,
        sourceNote: "Эквивалентный типовой слой для оконного блока с двухкамерным стеклопакетом; используется только для демонстрационного послойного расчета при отсутствии паспортного набора слоев.",
    },
    concrete: {
        id: "concrete",
        label: "Бетон",
        density_kg_m3: 2400,
        heatCapacity_kJ_kgK: 0.84,
        conductivityDry_W_mK: 1.51,
        conductivityA_W_mK: 1.74,
        conductivityB_W_mK: 1.86,
        heatAbsorptionA_W_m2K: 16.77,
        heatAbsorptionB_W_m2K: 17.88,
        vaporPermeability_mg_mhPa: 0.03,
        isApproximate: true,
        sourceNote: "Alias на тяжелый бетон для совместимости со старой библиотекой материалов.",
    },
    brick: {
        id: "brick",
        label: "Кирпич",
        density_kg_m3: 1400,
        heatCapacity_kJ_kgK: 0.88,
        conductivityDry_W_mK: 0.41,
        conductivityA_W_mK: 0.52,
        conductivityB_W_mK: 0.58,
        heatAbsorptionA_W_m2K: 7.01,
        heatAbsorptionB_W_m2K: 7.56,
        vaporPermeability_mg_mhPa: 0.16,
        isApproximate: true,
        sourceNote: "Alias на рабочий вариант керамического пустотного кирпича для обратной совместимости.",
    },
    gypsum: {
        id: "gypsum",
        label: "Гипсокартон",
        density_kg_m3: 800,
        heatCapacity_kJ_kgK: 0.84,
        conductivityDry_W_mK: 0.15,
        conductivityA_W_mK: 0.19,
        conductivityB_W_mK: 0.21,
        heatAbsorptionA_W_m2K: 3.34,
        heatAbsorptionB_W_m2K: 3.66,
        vaporPermeability_mg_mhPa: 0.075,
        isApproximate: true,
        sourceNote: "Alias на гипсокартон для обратной совместимости.",
    },
    polystyrene: {
        id: "polystyrene",
        label: "Пенополистирол",
        density_kg_m3: 25,
        heatCapacity_kJ_kgK: 1.34,
        conductivityDry_W_mK: 0.039,
        conductivityA_W_mK: 0.041,
        conductivityB_W_mK: 0.051,
        heatAbsorptionA_W_m2K: 0.29,
        heatAbsorptionB_W_m2K: 0.32,
        vaporPermeability_mg_mhPa: 0.05,
        isApproximate: true,
        sourceNote: "Alias на EPS.",
    },
    // --- Дополнительные материалы ---
    lime_plaster: {
        id: "lime_plaster",
        label: "Штукатурка известковая",
        density_kg_m3: 1600,
        heatCapacity_kJ_kgK: 0.88,
        conductivityDry_W_mK: 0.40,
        conductivityA_W_mK: 0.47,
        conductivityB_W_mK: 0.58,
        heatAbsorptionA_W_m2K: 7.28,
        heatAbsorptionB_W_m2K: 8.14,
        vaporPermeability_mg_mhPa: 0.12,
        sourceNote: "СП 50.13330.2024 Прил. М; раствор известковый ρ=1600 кг/м³.",
    },
    hollow_ceramic_block: {
        id: "hollow_ceramic_block",
        label: "Блок керамический поризованный (Porotherm)",
        density_kg_m3: 730,
        heatCapacity_kJ_kgK: 0.84,
        conductivityDry_W_mK: 0.15,
        conductivityA_W_mK: 0.17,
        conductivityB_W_mK: 0.20,
        heatAbsorptionA_W_m2K: 3.05,
        heatAbsorptionB_W_m2K: 3.45,
        vaporPermeability_mg_mhPa: 0.14,
        isApproximate: true,
        sourceNote: "Типовые значения для поризованного керамического блока Porotherm 38 ρ≈730 кг/м³; λ_A=0.17 Вт/(м·К) — по тех. документации Wienerberger.",
    },
    osb: {
        id: "osb",
        label: "OSB (ориентированно-стружечная плита)",
        density_kg_m3: 650,
        heatCapacity_kJ_kgK: 1.70,
        conductivityDry_W_mK: 0.12,
        conductivityA_W_mK: 0.13,
        conductivityB_W_mK: 0.15,
        heatAbsorptionA_W_m2K: 3.86,
        heatAbsorptionB_W_m2K: 4.24,
        vaporPermeability_mg_mhPa: 0.03,
        sourceNote: "OSB/3 по EN 300; λ≈0.13 Вт/(м·К) — типовое значение производителей (Kronospan, Egger).",
    },
    steel_sheet: {
        id: "steel_sheet",
        label: "Сталь листовая (дверная обшивка)",
        density_kg_m3: 7850,
        heatCapacity_kJ_kgK: 0.48,
        conductivityDry_W_mK: 58.0,
        conductivityA_W_mK: 58.0,
        conductivityB_W_mK: 58.0,
        heatAbsorptionA_W_m2K: 126.0,
        heatAbsorptionB_W_m2K: 126.0,
        vaporPermeability_mg_mhPa: 0,
        sourceNote: "Листовая конструкционная сталь; используется для расчёта слоёв металлических дверей.",
    },
    slag_wool: {
        id: "slag_wool",
        label: "Шлаковата (минеральная вата на шлаковой основе)",
        density_kg_m3: 200,
        heatCapacity_kJ_kgK: 0.84,
        conductivityDry_W_mK: 0.043,
        conductivityA_W_mK: 0.046,
        conductivityB_W_mK: 0.052,
        heatAbsorptionA_W_m2K: 0.62,
        heatAbsorptionB_W_m2K: 0.70,
        vaporPermeability_mg_mhPa: 0.50,
        sourceNote: "СП 50.13330.2024 Прил. М; шлаковата ρ=200 кг/м³.",
    },
    foam_glass: {
        id: "foam_glass",
        label: "Пеностекло (теплоизоляционные плиты)",
        density_kg_m3: 200,
        heatCapacity_kJ_kgK: 0.84,
        conductivityDry_W_mK: 0.060,
        conductivityA_W_mK: 0.068,
        conductivityB_W_mK: 0.075,
        heatAbsorptionA_W_m2K: 1.08,
        heatAbsorptionB_W_m2K: 1.18,
        vaporPermeability_mg_mhPa: 0,
        sourceNote: "Пеностекло ГОСТ Р 57153; λ_A=0.068 Вт/(м·К); паронепроницаемо — применяется для кровли и цоколя.",
    },
    expanded_clay_aggregate: {
        id: "expanded_clay_aggregate",
        label: "Керамзит (засыпка)",
        density_kg_m3: 400,
        heatCapacity_kJ_kgK: 0.84,
        conductivityDry_W_mK: 0.099,
        conductivityA_W_mK: 0.12,
        conductivityB_W_mK: 0.14,
        heatAbsorptionA_W_m2K: 1.85,
        heatAbsorptionB_W_m2K: 2.08,
        vaporPermeability_mg_mhPa: 0.21,
        sourceNote: "СП 50.13330.2024 Прил. М; керамзит фракционный ρ=400 кг/м³; применяется как засыпной утеплитель.",
    },
    glued_laminated_timber: {
        id: "glued_laminated_timber",
        label: "Брус клееный (CLT / клееный брус)",
        density_kg_m3: 500,
        heatCapacity_kJ_kgK: 2.30,
        conductivityDry_W_mK: 0.10,
        conductivityA_W_mK: 0.13,
        conductivityB_W_mK: 0.17,
        heatAbsorptionA_W_m2K: 3.87,
        heatAbsorptionB_W_m2K: 4.54,
        vaporPermeability_mg_mhPa: 0.05,
        sourceNote: "Клееный деревянный брус/CLT по ГОСТ 33124; λ_A≈0.13 Вт/(м·К).",
    },
    // --- Кровельные материалы ---
    bitumen_roll: {
        id: "bitumen_roll",
        label: "Рулонная битумная кровля (изопласт / ТехноНиколь)",
        density_kg_m3: 1100,
        heatCapacity_kJ_kgK: 1.47,
        conductivityDry_W_mK: 0.17,
        conductivityA_W_mK: 0.17,
        conductivityB_W_mK: 0.17,
        heatAbsorptionA_W_m2K: 5.99,
        heatAbsorptionB_W_m2K: 5.99,
        vaporPermeability_mg_mhPa: 0.008,
        sourceNote: "СП 50.13330.2024 Прил. М; рулонные кровельные и гидроизоляционные материалы на битумной основе ρ=1100 кг/м³; практически паронепроницаемы.",
    },
    rubber_membrane: {
        id: "rubber_membrane",
        label: "Мембрана ПВХ / EPDM / ТПО",
        density_kg_m3: 1300,
        heatCapacity_kJ_kgK: 1.00,
        conductivityDry_W_mK: 0.23,
        conductivityA_W_mK: 0.23,
        conductivityB_W_mK: 0.23,
        heatAbsorptionA_W_m2K: 5.47,
        heatAbsorptionB_W_m2K: 5.47,
        vaporPermeability_mg_mhPa: 0.001,
        sourceNote: "Синтетическая полимерная кровельная мембрана (ПВХ, EPDM, ТПО) ρ≈1300 кг/м³; λ≈0.23 Вт/(м·К); практически нулевая паропроницаемость.",
    },
    green_roof_substrate: {
        id: "green_roof_substrate",
        label: "Субстрат зелёной кровли (почвогрунт)",
        density_kg_m3: 900,
        heatCapacity_kJ_kgK: 2.09,
        conductivityDry_W_mK: 0.35,
        conductivityA_W_mK: 0.40,
        conductivityB_W_mK: 0.52,
        heatAbsorptionA_W_m2K: 7.66,
        heatAbsorptionB_W_m2K: 9.12,
        vaporPermeability_mg_mhPa: 0.17,
        sourceNote: "Типовой почвогрунтовый субстрат для экстенсивной зелёной кровли ρ≈900 кг/м³; λ_A=0.40 Вт/(м·К); по данным FLL Richtlinie Dachbegrünung.",
    },
    parquet: {
        id: "parquet",
        label: "Паркет / ламинат (деревянный пол)",
        density_kg_m3: 600,
        heatCapacity_kJ_kgK: 2.30,
        conductivityDry_W_mK: 0.12,
        conductivityA_W_mK: 0.14,
        conductivityB_W_mK: 0.18,
        heatAbsorptionA_W_m2K: 4.22,
        heatAbsorptionB_W_m2K: 4.73,
        vaporPermeability_mg_mhPa: 0.05,
        sourceNote: "Паркетная доска / ламинат ρ=600 кг/м³; λ_A=0.14 Вт/(м·К) — по СП 50.13330.2024 Прил. М (древесина поперёк волокон).",
    },
    ceramic_tile: {
        id: "ceramic_tile",
        label: "Керамическая плитка (напольная)",
        density_kg_m3: 1800,
        heatCapacity_kJ_kgK: 0.84,
        conductivityDry_W_mK: 1.00,
        conductivityA_W_mK: 1.05,
        conductivityB_W_mK: 1.16,
        heatAbsorptionA_W_m2K: 12.52,
        heatAbsorptionB_W_m2K: 13.44,
        vaporPermeability_mg_mhPa: 0.0,
        sourceNote: "Керамическая облицовочная плитка ρ=1800 кг/м³; λ_A=1.05 Вт/(м·К); паронепроницаема.",
    },
    sand_gravel: {
        id: "sand_gravel",
        label: "Песчано-гравийная подготовка",
        density_kg_m3: 1700,
        heatCapacity_kJ_kgK: 0.84,
        conductivityDry_W_mK: 0.33,
        conductivityA_W_mK: 0.42,
        conductivityB_W_mK: 0.52,
        heatAbsorptionA_W_m2K: 7.01,
        heatAbsorptionB_W_m2K: 7.68,
        vaporPermeability_mg_mhPa: 0.17,
        sourceNote: "Песчано-гравийная смесь ρ=1700 кг/м³; λ_A=0.42 Вт/(м·К); применяется как подготовка под плиту пола по грунту по СП 22.",
    },
    acoustic_mat: {
        id: "acoustic_mat",
        label: "Звукоизоляционная подложка (ЗИПС/VibroStop)",
        density_kg_m3: 100,
        heatCapacity_kJ_kgK: 1.47,
        conductivityDry_W_mK: 0.040,
        conductivityA_W_mK: 0.043,
        conductivityB_W_mK: 0.047,
        heatAbsorptionA_W_m2K: 0.56,
        heatAbsorptionB_W_m2K: 0.62,
        vaporPermeability_mg_mhPa: 0.35,
        isApproximate: true,
        sourceNote: "Звукоизолирующая подложка (минватный или пенополиэтиленовый мат) ρ≈100 кг/м³; λ_A≈0.043 Вт/(м·К); применяется под стяжку или паркет.",
    },
    concrete_screed: {
        id: "concrete_screed",
        label: "Цементно-песчаная стяжка (тонкая)",
        density_kg_m3: 1800,
        heatCapacity_kJ_kgK: 0.84,
        conductivityDry_W_mK: 0.58,
        conductivityA_W_mK: 0.76,
        conductivityB_W_mK: 0.93,
        heatAbsorptionA_W_m2K: 9.6,
        heatAbsorptionB_W_m2K: 11.09,
        vaporPermeability_mg_mhPa: 0.09,
        isApproximate: true,
        sourceNote: "Alias на цементно-песчаный раствор; используется как балластная стяжка кровли или защитный слой над утеплителем.",
    },
};
export function getMaterialThermalProperties(input) {
    const material = MATERIALS[input.materialId];
    if (!material) {
        return null;
    }
    const operationCondition = input.operationCondition ?? "A";
    return {
        ...material,
        conductivity_W_mK: operationCondition === "A" ? material.conductivityA_W_mK : material.conductivityB_W_mK,
        heatAbsorption_W_m2K: operationCondition === "A" ? material.heatAbsorptionA_W_m2K : material.heatAbsorptionB_W_m2K,
    };
}
export { MATERIALS as MATERIAL_THERMAL_PROPERTIES };
