import { runTests } from "./testHarness.js";

import "./geometry/bimPipeline.test.js";
import "./geometry/dedupeRoomVolumes.test.js";
import "./demo/demoVKRScenario.test.js";
import "./demo/videoDemoHouse.test.js";
import "./build/demoVideoProject.test.js";
import "./build/pruneSubdividedManualRooms.test.js";
import "./build/thermalPanelPersistence.test.js";
import "./build/spReportPdf.test.js";
import "./build/thermalSimulationPanelHelpers.test.js";
import "./economics/economicAnalysis.test.js";
import "./economics/scenarioEnergyTariff.test.js";
import "./economics/resolveScenarioEcologyEmission.test.js";
import "./economics/resolveScenarioEconomy.test.js";
import "./networks/engineering2dSymbols.test.js";
import "./networks/networkPresentation.test.js";
import "./view3d/equipmentMeshes.test.js";
import "./view3d/engineeringOverview.test.js";
import "./view3d/build3dPreviewImport.test.js";
import "./view3d/stablePreview.test.js";
import "./view3d/stablePreviewControls.test.js";
import "./view3d/surfaceFieldHoverLabels.test.js";
import "./view3d/stablePreviewMath.test.js";
import "./view3d/simplePreviewMath.test.js";
import "./view3d/buildSimple3DModel.test.js";
import "./view3d/recoveredPreviewMath.test.js";
import "./view3d/buildRecovered3DModel.test.js";
import "./view3d/recoveredMeshAudit.test.js";
import "./view3d/buildCanonical3DModel.test.js";
import "./view3d/build3dRenderPath.test.js";
import "./view3d/wallJoins.test.js";
import "./ui/mojibake.test.js";
import "./ui/resultsRender.test.js";
import "./geometry/polygonArea.test.js";
import "./thermal/singleZone.test.js";
import "./thermal/infiltrationModes.test.js";
import "./thermal/formulaHelpers.test.js";
import "./thermal/surfaceField.test.js";
import "./thermal/wallFacadeAndDiagnostics.test.js";
import "./thermal/buildingPerformanceMetrics.test.js";
import "./thermal/occupancyPresets.test.js";
import "./thermal/resolveScenarioComfort.test.js";
import "./thermal/resolveScenarioVentilation.test.js";
import "./thermal/resolveSeasonalWindSpeed.test.js";
import "./thermal/resolveScenarioEngineering.test.js";
import "./thermal/thermalResultsChartPayload.test.js";
import "./thermal/transient1D.test.js";
import "./thermal/transientMonteCarlo.test.js";
import "./thermal/transientVisualization.test.js";
import "./thermal/engineeringAnalysis.test.js";
import "./thermal/sp50Compliance.test.js";
import "./thermal/thermalConsistencyCheck.test.js";
import "./thermal/temperatureSeries.test.js";
import "./thermal/twinGraphHeuristics.test.js";
import "./sp50/energyCharacteristic.test.js";
import "./formulas/registryReferences.test.js";
import "./thermal/zoneAnalysis.test.js";
import "./ai/aiEngine.test.js";
import "./reports/exportGenerators.test.js";
import "./reports/demoExportQa.test.js";
import "./reports/demoDefaults.test.js";
import "./reports/demoExportDocumentQuality.test.js";
import "./reports/expertiseInputs.test.js";
import "./scenarios/sourceDataWorkspace.test.js";
import "./demo/videoDemoThermalBridges.test.js";
import "./shared/bridgeAccountingMode.test.js";
import "./shared/homogeneityFromModel.test.js";
import "./shared/roomNames.test.js";
import "./shared/openingShadingFactor.test.js";
import "./shared/solarShading.test.js";

runTests().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
