/** Теплотворная способность природного газа (низшая), кВт·ч/м³ */
export const GAS_LCV_KWH_PER_M3 = 9.3;
/** КПД стандартного газового котла (используется для пересчёта тарифа в руб./кВт·ч тепла) */
export const DEFAULT_BOILER_EFFICIENCY = 0.92;
/** Переводит тариф на газ руб./м³ → руб./кВт·ч тепловой энергии на выходе котла */
export function gasM3TariffToKwh(tariffRubPerM3, efficiency = DEFAULT_BOILER_EFFICIENCY) {
    if (tariffRubPerM3 <= 0 || efficiency <= 0) {
        return 0;
    }
    return tariffRubPerM3 / (GAS_LCV_KWH_PER_M3 * efficiency);
}
export const CITY_ENERGY_PROFILES = [
    // ─── Европейская часть ───────────────────────────────────────────────────
    {
        cityId: "moscow",
        heatTariffRubPerGcal: 3200,
        electricityTariffRubPerKwh: 5.8,
        gasTariffRubPerM3: 7.4,
        gasAvailable: true,
        gasUnderconsumptionPenaltyPercent: 30,
        gasMinimumOfftakePercent: 70,
        heatContractMinimumPaymentFraction: 0.10,
        constructionCostFactor: 1.00,
    },
    {
        cityId: "spb",
        heatTariffRubPerGcal: 3100,
        electricityTariffRubPerKwh: 5.5,
        gasTariffRubPerM3: 7.2,
        gasAvailable: true,
        gasUnderconsumptionPenaltyPercent: 28,
        gasMinimumOfftakePercent: 70,
        heatContractMinimumPaymentFraction: 0.12,
        constructionCostFactor: 0.95,
    },
    {
        cityId: "voronezh",
        heatTariffRubPerGcal: 2600,
        electricityTariffRubPerKwh: 4.5,
        gasTariffRubPerM3: 7.0,
        gasAvailable: true,
        gasUnderconsumptionPenaltyPercent: 25,
        gasMinimumOfftakePercent: 70,
        heatContractMinimumPaymentFraction: 0.15,
        constructionCostFactor: 0.76,
    },
    {
        cityId: "nizhny_novgorod",
        heatTariffRubPerGcal: 2750,
        electricityTariffRubPerKwh: 4.5,
        gasTariffRubPerM3: 7.0,
        gasAvailable: true,
        gasUnderconsumptionPenaltyPercent: 25,
        gasMinimumOfftakePercent: 70,
        heatContractMinimumPaymentFraction: 0.15,
        constructionCostFactor: 0.82,
    },
    {
        cityId: "kazan",
        heatTariffRubPerGcal: 2500,
        electricityTariffRubPerKwh: 3.7,
        gasTariffRubPerM3: 6.8,
        gasAvailable: true,
        gasUnderconsumptionPenaltyPercent: 22,
        gasMinimumOfftakePercent: 70,
        heatContractMinimumPaymentFraction: 0.15,
        constructionCostFactor: 0.80,
    },
    {
        cityId: "samara",
        heatTariffRubPerGcal: 2600,
        electricityTariffRubPerKwh: 3.9,
        gasTariffRubPerM3: 6.5,
        gasAvailable: true,
        gasUnderconsumptionPenaltyPercent: 22,
        gasMinimumOfftakePercent: 70,
        heatContractMinimumPaymentFraction: 0.15,
        constructionCostFactor: 0.79,
    },
    {
        cityId: "ufa",
        heatTariffRubPerGcal: 2400,
        electricityTariffRubPerKwh: 3.5,
        gasTariffRubPerM3: 6.0,
        gasAvailable: true,
        gasUnderconsumptionPenaltyPercent: 20,
        gasMinimumOfftakePercent: 65,
        heatContractMinimumPaymentFraction: 0.18,
        constructionCostFactor: 0.78,
    },
    {
        cityId: "saratov",
        heatTariffRubPerGcal: 2550,
        electricityTariffRubPerKwh: 4.3,
        gasTariffRubPerM3: 6.8,
        gasAvailable: true,
        gasUnderconsumptionPenaltyPercent: 22,
        gasMinimumOfftakePercent: 70,
        heatContractMinimumPaymentFraction: 0.15,
        constructionCostFactor: 0.76,
    },
    {
        cityId: "volgograd",
        heatTariffRubPerGcal: 2500,
        electricityTariffRubPerKwh: 4.5,
        gasTariffRubPerM3: 6.7,
        gasAvailable: true,
        gasUnderconsumptionPenaltyPercent: 22,
        gasMinimumOfftakePercent: 70,
        heatContractMinimumPaymentFraction: 0.15,
        constructionCostFactor: 0.77,
    },
    {
        cityId: "rostov",
        heatTariffRubPerGcal: 3000,
        electricityTariffRubPerKwh: 4.8,
        gasTariffRubPerM3: 6.9,
        gasAvailable: true,
        gasUnderconsumptionPenaltyPercent: 25,
        gasMinimumOfftakePercent: 70,
        heatContractMinimumPaymentFraction: 0.12,
        constructionCostFactor: 0.82,
    },
    {
        cityId: "krasnodar",
        heatTariffRubPerGcal: 2900,
        electricityTariffRubPerKwh: 5.0,
        gasTariffRubPerM3: 6.5,
        gasAvailable: true,
        gasUnderconsumptionPenaltyPercent: 22,
        gasMinimumOfftakePercent: 70,
        heatContractMinimumPaymentFraction: 0.12,
        constructionCostFactor: 0.87,
    },
    // ─── Урал ────────────────────────────────────────────────────────────────
    {
        cityId: "ekb",
        heatTariffRubPerGcal: 2800,
        electricityTariffRubPerKwh: 4.2,
        gasTariffRubPerM3: 6.8,
        gasAvailable: true,
        gasUnderconsumptionPenaltyPercent: 25,
        gasMinimumOfftakePercent: 70,
        heatContractMinimumPaymentFraction: 0.15,
        constructionCostFactor: 0.85,
    },
    {
        cityId: "chelyabinsk",
        heatTariffRubPerGcal: 2650,
        electricityTariffRubPerKwh: 3.8,
        gasTariffRubPerM3: 6.5,
        gasAvailable: true,
        gasUnderconsumptionPenaltyPercent: 25,
        gasMinimumOfftakePercent: 70,
        heatContractMinimumPaymentFraction: 0.15,
        constructionCostFactor: 0.80,
    },
    {
        cityId: "perm",
        heatTariffRubPerGcal: 2700,
        electricityTariffRubPerKwh: 4.0,
        gasTariffRubPerM3: 6.5,
        gasAvailable: true,
        gasUnderconsumptionPenaltyPercent: 25,
        gasMinimumOfftakePercent: 70,
        heatContractMinimumPaymentFraction: 0.15,
        constructionCostFactor: 0.80,
    },
    // ─── Западная Сибирь ─────────────────────────────────────────────────────
    {
        cityId: "tyumen",
        heatTariffRubPerGcal: 2100,
        electricityTariffRubPerKwh: 2.5,
        gasTariffRubPerM3: 5.8,
        gasAvailable: true,
        gasUnderconsumptionPenaltyPercent: 18,
        gasMinimumOfftakePercent: 65,
        heatContractMinimumPaymentFraction: 0.10,
        constructionCostFactor: 0.92,
    },
    {
        cityId: "omsk",
        heatTariffRubPerGcal: 2200,
        electricityTariffRubPerKwh: 3.5,
        gasTariffRubPerM3: 7.2,
        gasAvailable: true,
        gasUnderconsumptionPenaltyPercent: 25,
        gasMinimumOfftakePercent: 70,
        heatContractMinimumPaymentFraction: 0.15,
        constructionCostFactor: 0.80,
    },
    {
        cityId: "novosibirsk",
        heatTariffRubPerGcal: 2700,
        electricityTariffRubPerKwh: 3.2,
        gasTariffRubPerM3: 7.5,
        gasAvailable: true,
        gasUnderconsumptionPenaltyPercent: 25,
        gasMinimumOfftakePercent: 70,
        heatContractMinimumPaymentFraction: 0.15,
        constructionCostFactor: 0.83,
    },
    {
        cityId: "tomsk",
        heatTariffRubPerGcal: 2300,
        electricityTariffRubPerKwh: 3.8,
        gasTariffRubPerM3: 7.3,
        gasAvailable: true,
        gasUnderconsumptionPenaltyPercent: 25,
        gasMinimumOfftakePercent: 70,
        heatContractMinimumPaymentFraction: 0.15,
        constructionCostFactor: 0.82,
    },
    // ─── Восточная Сибирь и ДВ ───────────────────────────────────────────────
    {
        cityId: "krasnoyarsk",
        heatTariffRubPerGcal: 2200,
        electricityTariffRubPerKwh: 2.0,
        gasTariffRubPerM3: 0,
        gasAvailable: false,
        gasUnderconsumptionPenaltyPercent: 0,
        gasMinimumOfftakePercent: 0,
        heatContractMinimumPaymentFraction: 0.10,
        constructionCostFactor: 0.88,
    },
    {
        cityId: "irkutsk",
        heatTariffRubPerGcal: 1800,
        electricityTariffRubPerKwh: 1.2,
        gasTariffRubPerM3: 0,
        gasAvailable: false,
        gasUnderconsumptionPenaltyPercent: 0,
        gasMinimumOfftakePercent: 0,
        heatContractMinimumPaymentFraction: 0.10,
        constructionCostFactor: 0.85,
    },
    {
        cityId: "khabarovsk",
        heatTariffRubPerGcal: 2800,
        electricityTariffRubPerKwh: 4.0,
        gasTariffRubPerM3: 0,
        gasAvailable: false,
        gasUnderconsumptionPenaltyPercent: 0,
        gasMinimumOfftakePercent: 0,
        heatContractMinimumPaymentFraction: 0.12,
        constructionCostFactor: 0.90,
    },
];
const _profileIndex = new Map(CITY_ENERGY_PROFILES.map((p) => [p.cityId, p]));
export function getCityEnergyProfile(cityId) {
    if (!cityId) {
        return null;
    }
    return _profileIndex.get(cityId.trim().toLowerCase()) ?? null;
}
