export const economicDefaults = {
    region: "Россия",
    currency: "RUB",
    heatTariffRubPerGcal: 3500,
    electricityTariffRubPerKwh: 6,
    regionalCostFactor: 1,
    measures: {
        wallInsulationMineralWool: {
            name: "Утепление наружных стен минеральной ватой",
            unit: "м²",
            materialCostRubM2: [500, 900],
            workCostRubM2: [1200, 2000],
            totalCostRubM2: [1800, 4000],
            expectedHeatLossReductionPercent: [25, 45],
            complexity: "средняя",
            comfortEffect: "высокий",
            riskReduction: "снижение риска промерзания и конденсата",
            lifetimeYears: 30,
        },
        wallInsulationPolystyrene: {
            name: "Утепление наружных стен пенополистиролом",
            unit: "м²",
            materialCostRubM2: [450, 850],
            workCostRubM2: [1100, 1800],
            totalCostRubM2: [1700, 3600],
            expectedHeatLossReductionPercent: [22, 40],
            complexity: "средняя",
            comfortEffect: "высокий",
            riskReduction: "снижение риска промерзания при корректном узле пароизоляции",
            lifetimeYears: 30,
        },
        wetFacade: {
            name: "Система мокрого фасада",
            unit: "м²",
            totalCostRubM2: [2000, 6000],
            expectedHeatLossReductionPercent: [30, 50],
            complexity: "средняя/высокая",
            comfortEffect: "высокий",
            riskReduction: "снижение мостиков холода в зоне фасада",
            lifetimeYears: 25,
        },
        ventilatedFacade: {
            name: "Вентилируемый фасад с утеплителем",
            unit: "м²",
            totalCostRubM2: [3500, 7500],
            expectedHeatLossReductionPercent: [28, 48],
            complexity: "высокая",
            comfortEffect: "высокий",
            riskReduction: "снижение риска увлажнения ограждения и локального промерзания",
            lifetimeYears: 30,
        },
        roofInsulationMineralWool: {
            name: "Утепление кровли или чердачного перекрытия минеральной ватой",
            unit: "м²",
            totalCostRubM2: [1500, 4000],
            expectedHeatLossReductionPercent: [15, 30],
            complexity: "средняя",
            comfortEffect: "высокий",
            riskReduction: "снижение риска конденсата на покрытии",
            lifetimeYears: 25,
        },
        roofInsulationBasalt: {
            name: "Утепление кровли базальтовой ватой",
            unit: "м²",
            totalCostRubM2: [1800, 4300],
            expectedHeatLossReductionPercent: [18, 32],
            complexity: "средняя",
            comfortEffect: "высокий",
            riskReduction: "уменьшение локального переохлаждения верхних помещений",
            lifetimeYears: 25,
        },
        coldAtticInsulation: {
            name: "Утепление холодного чердака",
            unit: "м²",
            totalCostRubM2: [900, 2600],
            expectedHeatLossReductionPercent: [12, 25],
            complexity: "низкая",
            comfortEffect: "средний/высокий",
            riskReduction: "снижение риска увлажнения чердачного перекрытия",
            lifetimeYears: 20,
        },
        floorInsulation: {
            name: "Утепление пола или перекрытия над подвалом",
            unit: "м²",
            totalCostRubM2: [1600, 4200],
            expectedHeatLossReductionPercent: [15, 35],
            complexity: "средняя",
            comfortEffect: "высокий",
            riskReduction: "снижение риска холодного пола и конденсата у цоколя",
            lifetimeYears: 25,
        },
        windowReplacement: {
            name: "Замена окон на энергоэффективные",
            unit: "м²",
            totalCostRubM2: [8000, 18000],
            expectedHeatLossReductionPercent: [10, 25],
            complexity: "средняя",
            comfortEffect: "высокий",
            riskReduction: "снижение риска продувания и переохлаждения откосов",
            lifetimeYears: 20,
        },
        energyGlassUnit: {
            name: "Установка энергосберегающего стеклопакета",
            unit: "м²",
            totalCostRubM2: [5500, 12000],
            expectedHeatLossReductionPercent: [8, 18],
            complexity: "средняя",
            comfortEffect: "высокий",
            riskReduction: "снижение риска конденсата на стекле",
            lifetimeYears: 20,
        },
        jointsSealing: {
            name: "Герметизация оконных примыканий",
            unit: "м²",
            totalCostRubM2: [350, 1200],
            expectedHeatLossReductionPercent: [3, 8],
            complexity: "низкая",
            comfortEffect: "средний/высокий",
            riskReduction: "снижение риска продувания и увлажнения откосов",
            lifetimeYears: 5,
        },
        hardwareAdjustment: {
            name: "Регулировка фурнитуры и замена уплотнителей",
            unit: "комплекс",
            totalCostRub: [8000, 50000],
            expectedHeatLossReductionPercent: [3, 10],
            complexity: "низкая",
            comfortEffect: "средний",
            riskReduction: "снижение локального продувания и конденсата",
            lifetimeYears: 8,
        },
        sealingLeaks: {
            name: "Герметизация щелей и примыканий",
            unit: "комплекс",
            totalCostRub: [10000, 80000],
            expectedHeatLossReductionPercent: [5, 15],
            complexity: "низкая",
            comfortEffect: "средний/высокий",
            riskReduction: "снижение риска сквозняков, конденсата и плесени",
            lifetimeYears: 5,
        },
        doorInsulation: {
            name: "Утепление входной двери и восстановление уплотнителей",
            unit: "комплекс",
            totalCostRub: [12000, 90000],
            expectedHeatLossReductionPercent: [6, 18],
            complexity: "низкая",
            comfortEffect: "средний/высокий",
            riskReduction: "снижение риска продувания входной группы",
            lifetimeYears: 10,
        },
        vestibule: {
            name: "Установка тамбура или второй двери",
            unit: "комплекс",
            totalCostRub: [60000, 350000],
            expectedHeatLossReductionPercent: [10, 28],
            complexity: "средняя",
            comfortEffect: "высокий",
            riskReduction: "снижение пиковых инфильтрационных потерь",
            lifetimeYears: 30,
        },
        thermalBridgeMitigation: {
            name: "Локальное устранение мостиков холода",
            unit: "комплекс",
            totalCostRub: [40000, 250000],
            expectedHeatLossReductionPercent: [10, 35],
            complexity: "средняя",
            comfortEffect: "средний/высокий",
            riskReduction: "снижение риска промерзания, конденсата и плесени",
            lifetimeYears: 20,
        },
        heatingControl: {
            name: "Терморегуляторы и балансировка отопления",
            unit: "комплекс",
            totalCostRub: [30000, 200000],
            expectedEnergySavingPercent: [5, 20],
            complexity: "средняя",
            comfortEffect: "высокий",
            riskReduction: "снижение перегревов, недогрева и гидравлических перекосов",
            lifetimeYears: 15,
        },
        weatherControl: {
            name: "Погодозависимое регулирование",
            unit: "комплекс",
            totalCostRub: [50000, 250000],
            expectedEnergySavingPercent: [7, 18],
            complexity: "средняя",
            comfortEffect: "высокий",
            riskReduction: "снижение перетопов и температурных колебаний",
            lifetimeYears: 15,
        },
        pipeInsulation: {
            name: "Утепление трубопроводов в неотапливаемых зонах",
            unit: "комплекс",
            totalCostRub: [15000, 100000],
            expectedEnergySavingPercent: [2, 8],
            complexity: "низкая",
            comfortEffect: "средний",
            riskReduction: "снижение потерь и риска переохлаждения магистралей",
            lifetimeYears: 15,
        },
    },
};
