import { runTests } from "./testHarness.js";
import "./geometry/bimPipeline.test.js";
import "./demo/demoVKRScenario.test.js";
import "./demo/videoDemoHouse.test.js";
import "./build/demoVideoProject.test.js";
import "./build/thermalPanelPersistence.test.js";
import "./build/spReportPdf.test.js";
import "./build/thermalSimulationPanelHelpers.test.js";
import "./economics/economicAnalysis.test.js";
import "./networks/networkPresentation.test.js";
import "./view3d/equipmentMeshes.test.js";
import "./view3d/engineeringOverview.test.js";
import "./view3d/build3dPreviewImport.test.js";
import "./view3d/stablePreview.test.js";
import "./view3d/stablePreviewControls.test.js";
import "./view3d/stablePreviewMath.test.js";
import "./view3d/simplePreviewMath.test.js";
import "./view3d/buildSimple3DModel.test.js";
import "./view3d/recoveredPreviewMath.test.js";
import "./view3d/buildRecovered3DModel.test.js";
import "./view3d/recoveredMeshAudit.test.js";
import "./view3d/buildCanonical3DModel.test.js";
import "./view3d/build3dRenderPath.test.js";
import "./view3d/wallJoins.test.js";
import "./ui/mojibake.test.js";
import "./ui/resultsRender.test.js";
import "./geometry/polygonArea.test.js";
import "./thermal/singleZone.test.js";
import "./thermal/formulaHelpers.test.js";
import "./thermal/wallFacadeAndDiagnostics.test.js";
import "./thermal/transient1D.test.js";
import "./thermal/transientMonteCarlo.test.js";
import "./thermal/transientVisualization.test.js";
import "./thermal/engineeringAnalysis.test.js";
import "./thermal/sp50Compliance.test.js";
import "./thermal/zoneAnalysis.test.js";
import "./ai/aiEngine.test.js";
runTests().catch((error) => {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
});
