export const createEmptyBuildingModel = () => ({
    levels: [],
    rooms: [],
    walls: [],
    roofs: [],
    floorSlabs: [],
    doors: [],
    windows: [],
    pipes: [],
    ducts: [],
    equipment: [],
    sensors: [],
    scenarios: [],
    activeScenarioId: null,
    events: [],
    meta: {},
    thermalProtection: undefined,
});
