export type FormulaModule = "Geometry" | "Envelope" | "Thermal" | "Uncertainty" | "Calibration";
export type FormulaContour =
  | "geometry"
  | "rc-runtime"
  | "derived-only"
  | "normative-check"
  | "monte-carlo"
  | "economics"
  | "transient-1d"
  | "report-only"
  | "heuristic"
  | "legacy";
export type FormulaStatus =
  | "main-runtime"
  | "derived-only"
  | "normative-check"
  | "report-only"
  | "heuristic"
  | "legacy";

export interface FormulaVariable {
  key: string;
  symbolLatex?: string;
  label: string;
  unit?: string;
  source?: string;
}

export interface Formula {
  id: string;
  title: string;
  latex: string;
  titleRu?: string;
  formulaLatex?: string;
  description: string;
  variables: FormulaVariable[];
  module: FormulaModule;
  methodName: string;
  applicability: string;
  assumptions: string[];
  physicalMeaning: string;
  resultMeaning: string;
  contour?: FormulaContour;
  status?: FormulaStatus;
  sourceFiles?: string[];
  affectsSolver?: boolean;
  warnings?: string[];
  /** Нормативный или методический источник (СП, ГОСТ, учебник). */
  normReference?: string;
}

export interface Assumption {
  id: string;
  label: string;
  value: string;
  unit: string;
  description: string;
  source: string;
}

export const formulaModules: FormulaModule[] = ["Geometry", "Envelope", "Thermal", "Uncertainty", "Calibration"];
export const formulaContours: Array<{ id: FormulaContour; label: string }> = [
  { id: "geometry", label: "Геометрия" },
  { id: "rc-runtime", label: "RC solver" },
  { id: "derived-only", label: "Derived / diagnostics" },
  { id: "normative-check", label: "СП 50 / нормы" },
  { id: "monte-carlo", label: "Monte Carlo" },
  { id: "economics", label: "Экономика" },
  { id: "transient-1d", label: "1D transient" },
  { id: "report-only", label: "Только отчёт" },
  { id: "heuristic", label: "Эвристика" },
  { id: "legacy", label: "Legacy" },
];

export const formulaRegistry: Formula[] = [
  {
    id: "geom_polygon_area",
    module: "Geometry",
    title: "Площадь произвольного многоугольника",
    latex: String.raw`A = \frac{1}{2}\left|\sum_{i=1}^{n} x_i y_{i+1} - x_{i+1} y_i\right|`,
    description: "Формула шнуровки используется для расчета площади контура помещения на плане.",
    methodName: "Shoelace formula",
    applicability: "Плоские замкнутые полигоны без самопересечений.",
    assumptions: ["Контур замкнут", "Вершины перечислены по порядку обхода"],
    physicalMeaning: "Дает реальную геометрическую площадь помещения по координатам вершин.",
    resultMeaning: "Результат используется для объема, удельных нагрузок и инженерных расчетов.",
    variables: [
      { key: "area", symbolLatex: "A", label: "площадь полигона", unit: "м²", source: "выход" },
      { key: "vertex_coords", symbolLatex: "x_i, y_i", label: "координаты вершин", unit: "м", source: "геометрия модели" },
      { key: "vertex_count", symbolLatex: "n", label: "число вершин", source: "геометрия модели" },
    ],
  },
  {
    id: "geom_volume",
    module: "Geometry",
    title: "Объем помещения",
    latex: String.raw`V = A \cdot h`,
    description: "Объем помещения принимается как площадь пола, умноженная на высоту уровня.",
    methodName: "Призматическая геометрическая модель",
    applicability: "Помещения с постоянной высотой по плану.",
    assumptions: ["Высота помещения принимается равной высоте уровня или заданной высоте комнаты"],
    physicalMeaning: "Дает геометрический объем воздуха в помещении.",
    resultMeaning: "Используется для воздухообмена, теплоемкости воздуха и баланса теплоты.",
    variables: [
      { key: "volume", symbolLatex: "V", label: "объем помещения", unit: "м³", source: "выход" },
      { key: "area", symbolLatex: "A", label: "площадь пола", unit: "м²", source: "геометрия модели" },
      { key: "level_height", symbolLatex: "h", label: "высота помещения или уровня", unit: "м", source: "геометрия модели" },
    ],
  },
  {
    id: "layer_resistance",
    module: "Envelope",
    title: "Сопротивление теплопередаче слоя",
    latex: String.raw`R = \frac{d}{\lambda}`,
    description: "Термическое сопротивление однородного слоя рассчитывается по толщине и теплопроводности материала.",
    methodName: "Стационарная одномерная теплопроводность",
    applicability: "Однородные слои в плоской ограждающей конструкции.",
    assumptions: ["Материал слоя однороден", "Теплопередача рассматривается по толщине слоя"],
    physicalMeaning: "Показывает, насколько слой препятствует тепловому потоку.",
    resultMeaning: "Чем больше R, тем меньше теплопотери через слой при прочих равных.",
    variables: [
      { key: "resistance", symbolLatex: "R", label: "термическое сопротивление слоя", unit: "м²·К/Вт", source: "выход" },
      { key: "thickness", symbolLatex: "d", label: "толщина слоя", unit: "м", source: "материал/конструкция" },
      { key: "conductivity", symbolLatex: "\\lambda", label: "коэффициент теплопроводности", unit: "Вт/(м·К)", source: "материал" },
    ],
  },
  {
    id: "total_resistance",
    module: "Envelope",
    title: "Суммарное сопротивление и U-значение конструкции",
    latex: String.raw`R_{total} = R_{si} + \sum_i \frac{d_i}{\lambda_i} + R_{se}, \quad U = \frac{1}{R_{total}}`,
    description: "Сопротивления слоев и поверхностные сопротивления складываются, после чего находится U-значение ограждения.",
    methodName: "Расчет многослойной ограждающей конструкции",
    applicability: "Многослойные стены, покрытия, перекрытия при стационарном режиме.",
    assumptions: ["Слои соединены последовательно", "Используются эквивалентные поверхностные сопротивления"],
    physicalMeaning: "Связывает состав конструкции с общей теплопередачей через ограждение.",
    resultMeaning: "U используется далее в формуле потерь через ограждение.",
    variables: [
      { key: "r_total", symbolLatex: "R_{total}", label: "суммарное сопротивление теплопередаче", unit: "м²·К/Вт", source: "расчет" },
      { key: "r_si", symbolLatex: "R_{si}", label: "внутреннее поверхностное сопротивление", unit: "м²·К/Вт", source: "допущение/норма" },
      { key: "r_se", symbolLatex: "R_{se}", label: "наружное поверхностное сопротивление", unit: "м²·К/Вт", source: "допущение/норма" },
      { key: "u_value", symbolLatex: "U", label: "коэффициент теплопередачи", unit: "Вт/(м²·К)", source: "расчет" },
    ],
  },
  {
    id: "envelope_heat_loss",
    module: "Envelope",
    title: "Теплопотери через ограждение",
    latex: String.raw`\dot{Q} = U \cdot A \cdot (T_{in} - T_{out})`,
    description: "Стационарная инженерная формула для стены, окна, двери, пола, потолка и кровли.",
    methodName: "Формула стационарной теплопередачи через ограждение",
    applicability: "Стационарная или квазистационарная оценка потерь.",
    assumptions: ["Установившийся режим", "Используется эквивалентное U-значение элемента"],
    physicalMeaning: "Дает тепловой поток через конкретный элемент оболочки.",
    resultMeaning: "Результат показывает мощность теплопотерь в ваттах.",
    variables: [
      { key: "u_value", symbolLatex: "U", label: "коэффициент теплопередачи", unit: "Вт/(м²·К)", source: "конструкция/настройки" },
      { key: "area", symbolLatex: "A", label: "площадь элемента", unit: "м²", source: "геометрия модели" },
      { key: "t_in", symbolLatex: "T_{in}", label: "внутренняя температура", unit: "°C", source: "уставка/расчет" },
      { key: "t_out", symbolLatex: "T_{out}", label: "наружная температура", unit: "°C", source: "климат/сценарий" },
    ],
  },
  {
    id: "transmission_loss",
    module: "Envelope",
    title: "Стационарная теплопередача через оболочку",
    latex: String.raw`Q = U \cdot A \cdot \Delta T`,
    description: "Та же физическая зависимость, используемая в инженерном блоке результатов и объяснениях методики.",
    methodName: "Стационарная теплопередача",
    applicability: "Любой элемент оболочки, для которого задано U.",
    assumptions: ["Перепад температур считается заданным", "Поток одномерно усреднен через эквивалентное U"],
    physicalMeaning: "Связывает свойства оболочки, ее площадь и температурный напор.",
    resultMeaning: "Результат показывает вклад конкретного элемента в суммарные потери.",
    variables: [
      { key: "heat_flow", symbolLatex: "Q", label: "тепловой поток", unit: "Вт", source: "выход" },
      { key: "u_value", symbolLatex: "U", label: "коэффициент теплопередачи", unit: "Вт/(м²·К)", source: "конструкция/настройки" },
      { key: "area", symbolLatex: "A", label: "площадь конструкции", unit: "м²", source: "геометрия модели" },
      { key: "delta_t", symbolLatex: "\\Delta T", label: "разность температур внутри и снаружи", unit: "К", source: "расчет" },
    ],
  },
  {
    id: "envelope_infiltration",
    module: "Envelope",
    title: "Теплопотери на инфильтрацию",
    latex: String.raw`\dot{Q}_{inf} = \rho \, c_p \, \dot{V}_{inf} \, (T_{in} - T_{out})`,
    description: "Чувствительная теплота воздуха, теряемая на инфильтрационный приток наружного воздуха.",
    methodName: "Формула чувствительной теплоты воздуха",
    applicability: "Инфильтрация и неучтенный подсос наружного воздуха.",
    assumptions: ["Учитывается только чувствительная теплота", "Свойства воздуха принимаются постоянными"],
    physicalMeaning: "Определяет требуемую мощность на нагрев наружного воздуха до температуры помещения.",
    resultMeaning: "Результат показывает потери в ваттах из-за инфильтрации.",
    variables: [
      { key: "rho_air", symbolLatex: "\\rho", label: "плотность воздуха", unit: "кг/м³", source: "константа" },
      { key: "cp_air", symbolLatex: "c_p", label: "удельная теплоемкость воздуха", unit: "Дж/(кг·К)", source: "константа" },
      { key: "v_dot_inf", symbolLatex: "\\dot{V}_{inf}", label: "расход инфильтрации", unit: "м³/с", source: "кратность/объем" },
      { key: "delta_t", symbolLatex: "T_{in} - T_{out}", label: "разность температур", unit: "К", source: "расчет" },
    ],
  },
  {
    id: "ventilation_loss",
    module: "Envelope",
    title: "Теплопотери на вентиляцию",
    latex: String.raw`\dot{Q}_{vent} = \rho \, c_p \, L \, \Delta T, \quad L = \frac{nV}{3600}`,
    description: "Инженерная формула для механического воздухообмена, когда задана кратность или расход приточного воздуха.",
    methodName: "Формула чувствительной теплоты воздуха",
    applicability: "Механическая вентиляция и приточные системы без учета влагообмена.",
    assumptions: ["Воздух считается сухим", "Рекуперация тепла учитывается отдельно, если она есть"],
    physicalMeaning: "Связывает расход воздуха с тепловой нагрузкой на его нагрев.",
    resultMeaning: "Результат показывает потери на подогрев приточного воздуха.",
    variables: [
      { key: "q_vent", symbolLatex: "\\dot{Q}_{vent}", label: "потери на вентиляцию", unit: "Вт", source: "выход" },
      { key: "rho_air", symbolLatex: "\\rho", label: "плотность воздуха", unit: "кг/м³", source: "константа" },
      { key: "cp_air", symbolLatex: "c_p", label: "удельная теплоемкость воздуха", unit: "Дж/(кг·К)", source: "константа" },
      { key: "airflow", symbolLatex: "L", label: "объемный расход воздуха", unit: "м³/с", source: "вентиляция" },
      { key: "ach", symbolLatex: "n", label: "кратность воздухообмена", unit: "1/ч", source: "сценарий" },
      { key: "volume", symbolLatex: "V", label: "объем помещения", unit: "м³", source: "геометрия модели" },
    ],
  },
  {
    id: "thermal_balance",
    module: "Thermal",
    title: "Тепловой баланс помещения",
    latex: String.raw`Q_{balance} = Q_{gains} - Q_{losses}, \quad Q_{deficit} = \max(Q_{losses} - Q_{gains}, 0)`,
    description: "Итоговый стационарный баланс притоков и потерь в помещении.",
    methodName: "Стационарный тепловой баланс",
    applicability: "Инженерная оценка требуемой мощности отопления на расчетный момент.",
    assumptions: ["Притоки и потери суммируются по мощности", "Баланс относится к выбранному расчетному срезу"],
    physicalMeaning: "Показывает, хватает ли имеющихся теплопритоков для компенсации теплопотерь.",
    resultMeaning: "Q_deficit равен требуемой дополнительной мощности отопления.",
    variables: [
      { key: "q_balance", symbolLatex: "Q_{balance}", label: "итоговый тепловой баланс", unit: "Вт", source: "расчет" },
      { key: "q_gains", symbolLatex: "Q_{gains}", label: "сумма теплопритоков", unit: "Вт", source: "расчет" },
      { key: "q_losses", symbolLatex: "Q_{losses}", label: "сумма теплопотерь", unit: "Вт", source: "расчет" },
      { key: "q_deficit", symbolLatex: "Q_{deficit}", label: "требуемая мощность отопления", unit: "Вт", source: "выход" },
    ],
  },
  {
    id: "thermal_balance_room",
    module: "Thermal",
    title: "Тепловой баланс помещения",
    latex: String.raw`Q_{balance} = Q_{gains} - Q_{losses}`,
    description: "Короткая версия баланса для подсказок в редакторе и свойствах помещений.",
    methodName: "Стационарный тепловой баланс",
    applicability: "Быстрые подсказки в Build Mode и панели свойств.",
    assumptions: ["Используется тот же баланс, что и в инженерной вкладке результатов"],
    physicalMeaning: "Показывает знак избытка или дефицита теплоты в помещении.",
    resultMeaning: "Положительный баланс означает избыток, отрицательный - дефицит теплоты.",
    variables: [
      { key: "q_balance", symbolLatex: "Q_{balance}", label: "итоговый тепловой баланс", unit: "Вт", source: "расчет" },
      { key: "q_gains", symbolLatex: "Q_{gains}", label: "теплопритоки", unit: "Вт", source: "расчет" },
      { key: "q_losses", symbolLatex: "Q_{losses}", label: "теплопотери", unit: "Вт", source: "расчет" },
    ],
  },
  {
    id: "rc_lumped",
    module: "Thermal",
    title: "Сосредоточенная RC-модель помещения",
    latex: String.raw`C_{eff}\frac{dT}{dt} = Q_{in} - Q_{out}, \quad T_{k+1} = T_k + \frac{\Delta t}{C_{eff}}(Q_{in} - Q_{out})`,
    description: "Модель первого порядка используется для прогноза температуры и сценарного сравнения.",
    methodName: "Lumped capacitance / RC model",
    applicability: "Прогноз средней температуры помещения во времени.",
    assumptions: ["Помещение описывается одной усредненной температурой", "Температурное поле по объему не разрешается"],
    physicalMeaning: "Определяет изменение средней температуры по балансу мощностей и эффективной теплоемкости.",
    resultMeaning: "Результат показывает, как будет меняться средняя температура помещения шаг за шагом.",
    variables: [
      { key: "c_eff", symbolLatex: "C_{eff}", label: "эффективная теплоемкость", unit: "Дж/К", source: "расчет" },
      { key: "temperature", symbolLatex: "T_k", label: "температура на текущем шаге", unit: "°C", source: "состояние модели" },
      { key: "next_temperature", symbolLatex: "T_{k+1}", label: "температура на следующем шаге", unit: "°C", source: "выход" },
      { key: "time_step", symbolLatex: "\\Delta t", label: "шаг по времени", unit: "с", source: "настройки расчета" },
      { key: "q_in", symbolLatex: "Q_{in}", label: "теплопритоки", unit: "Вт", source: "расчет" },
      { key: "q_out", symbolLatex: "Q_{out}", label: "теплопотери", unit: "Вт", source: "расчет" },
    ],
  },
  {
    id: "steady_field",
    module: "Thermal",
    title: "Стационарное температурное поле на сетке",
    latex: String.raw`\nabla \cdot (k_{eff}\nabla T) + q = 0, \quad T_{i,j} = \frac{T_E + T_W + T_N + T_S + q_{i,j}h^2/k_{eff}}{4}`,
    description: "Температурная карта строится конечно-разностным методом на равномерной 2D-сетке.",
    methodName: "Пятиточечная конечно-разностная схема",
    applicability: "Плановая стационарная карта температуры помещения.",
    assumptions: ["Рассматривается 2D-проекция", "Используется эффективная плановая теплопроводность/диффузия"],
    physicalMeaning: "Оценивает распределение температуры по плану с учетом источников и граничных условий.",
    resultMeaning: "Результат показывает локальные холодные и теплые зоны на сетке.",
    variables: [
      { key: "k_eff", symbolLatex: "k_{eff}", label: "эффективная теплопроводность", unit: "Вт/(м·К)", source: "модель поля" },
      { key: "q_source", symbolLatex: "q", label: "объемный источник теплоты", unit: "Вт/м³", source: "источники тепла" },
      { key: "grid_step", symbolLatex: "h", label: "шаг сетки", unit: "м", source: "настройки расчета" },
      { key: "temperature", symbolLatex: "T", label: "температура", unit: "°C", source: "решатель" },
    ],
  },
  {
    id: "boundary_conditions",
    module: "Thermal",
    title: "Граничные условия теплопроводности",
    latex: String.raw`T = T_{boundary}; \quad -k\frac{\partial T}{\partial n} = q_n; \quad -k\frac{\partial T}{\partial n} = h(T_{surface} - T_{air})`,
    description: "Для расчета поля допускаются условия Дирихле, Неймана и Робина; в текущей карте используются фиксированные температуры поверхностей.",
    methodName: "Граничные условия Дирихле, Неймана и Робина",
    applicability: "Постановка стационарной задачи теплопроводности.",
    assumptions: ["В текущем интерфейсе карта использует упрощенное фиксирование температур внутренних поверхностей"],
    physicalMeaning: "Определяет, как расчетная область обменивается теплом с границами и средой.",
    resultMeaning: "От выбора граничных условий зависит форма температурного поля и уровень локальных экстремумов.",
    variables: [
      { key: "t_boundary", symbolLatex: "T_{boundary}", label: "заданная температура границы", unit: "°C", source: "граничные условия" },
      { key: "heat_flux", symbolLatex: "q_n", label: "нормальный тепловой поток", unit: "Вт/м²", source: "граничные условия" },
      { key: "h_coeff", symbolLatex: "h", label: "коэффициент теплоотдачи", unit: "Вт/(м²·К)", source: "граничные условия" },
    ],
  },
  {
    id: "radiator_heat_output",
    module: "Thermal",
    title: "Тепловая мощность отопительного прибора",
    latex: String.raw`Q_{emit} = \dot{m} \, c_p \, (T_{supply} - T_{return})`,
    description: "Упрощенная оценка мощности водяного отопительного прибора по расходу и перепаду температур теплоносителя.",
    methodName: "Баланс теплоты теплоносителя",
    applicability: "Радиаторы, конвекторы и водяные отопительные контуры.",
    assumptions: [
      "Потери по трассе не выделяются отдельно в формуле прибора",
      "Свойства теплоносителя принимаются постоянными",
      "В текущей версии используется для инженерной оценки оборудования и derived hydronic metrics",
    ],
    physicalMeaning: "Связывает расход теплоносителя и его охлаждение с полезной тепловой мощностью прибора.",
    resultMeaning: "Результат показывает доступную тепловую мощность отопительного элемента.",
    variables: [
      { key: "power", symbolLatex: "Q_{emit}", label: "тепловая мощность прибора", unit: "Вт", source: "выход" },
      { key: "mass_flow", symbolLatex: "\\dot{m}", label: "массовый расход теплоносителя", unit: "кг/с", source: "сеть" },
      { key: "cp", symbolLatex: "c_p", label: "удельная теплоемкость теплоносителя", unit: "Дж/(кг·К)", source: "константа" },
      { key: "t_supply", symbolLatex: "T_{supply}", label: "температура подачи", unit: "°C", source: "сеть" },
      { key: "t_return", symbolLatex: "T_{return}", label: "температура обратки", unit: "°C", source: "сеть" },
    ],
  },
  {
    id: "coolant_flow_rate",
    module: "Thermal",
    title: "Расход теплоносителя по тепловой нагрузке",
    latex: String.raw`\dot{m} = \frac{Q}{c_p (T_{supply} - T_{return})}`,
    description: "Расход теплоносителя определяется по требуемой тепловой мощности и расчетному перепаду температур.",
    methodName: "Баланс теплоты теплоносителя",
    applicability: "Подбор ветвей отопления и водяных контуров.",
    assumptions: [
      "Теплоемкость теплоносителя принимается постоянной",
      "Перепад температур задан расчетом",
      "В текущей версии используется для derived hydronic metrics, а не как обязательный режим solver",
    ],
    physicalMeaning: "Показывает, какой расход нужен для переноса заданной тепловой мощности.",
    resultMeaning: "Результат используется для подбора труб и насосов.",
    variables: [
      { key: "mass_flow", symbolLatex: "\\dot{m}", label: "массовый расход теплоносителя", unit: "кг/с", source: "выход" },
      { key: "power", symbolLatex: "Q", label: "тепловая нагрузка", unit: "Вт", source: "нагрузка/расчет" },
      { key: "cp", symbolLatex: "c_p", label: "удельная теплоемкость теплоносителя", unit: "Дж/(кг·К)", source: "константа" },
      { key: "delta_t", symbolLatex: "T_{supply} - T_{return}", label: "перепад температур", unit: "К", source: "система отопления" },
    ],
  },
  {
    id: "airflow_rate",
    module: "Thermal",
    title: "Расход воздуха по кратности",
    latex: String.raw`L = \frac{nV}{3600}`,
    description: "Объемный расход воздуха определяется по кратности воздухообмена и объему помещения.",
    methodName: "Связь кратности и расхода воздуха",
    applicability: "Приточная и вытяжная вентиляция, быстрые инженерные оценки.",
    assumptions: ["Воздухообмен считается равномерным по помещению"],
    physicalMeaning: "Показывает, сколько воздуха подается или удаляется в единицу времени.",
    resultMeaning: "Результат используется в расчете вентиляционных потерь и подборе воздуховодов.",
    variables: [
      { key: "airflow", symbolLatex: "L", label: "объемный расход воздуха", unit: "м³/с", source: "выход" },
      { key: "ach", symbolLatex: "n", label: "кратность воздухообмена", unit: "1/ч", source: "сценарий" },
      { key: "volume", symbolLatex: "V", label: "объем помещения", unit: "м³", source: "геометрия модели" },
    ],
  },
  {
    id: "pressure_drop_simple",
    module: "Thermal",
    title: "Потеря давления по длине участка",
    latex: String.raw`\Delta p = R_l \, l`,
    description: "Упрощенная инженерная форма для оценки потери давления на прямом участке сети по известному удельному сопротивлению.",
    methodName: "Линейная оценка потерь давления",
    applicability: "Предварительный подбор насосов и воздуховодов на ранней стадии проекта.",
    assumptions: ["Удельное сопротивление участка известно или взято из расчета/таблицы", "Местные сопротивления учитываются отдельно"],
    physicalMeaning: "Показывает, сколько давления теряется на заданной длине трассы.",
    resultMeaning: "Результат используется для выбора насоса или вентилятора.",
    variables: [
      { key: "delta_p", symbolLatex: "\\Delta p", label: "потеря давления", unit: "Па", source: "выход" },
      { key: "r_l", symbolLatex: "R_l", label: "удельная потеря давления на длину", unit: "Па/м", source: "расчет/таблица" },
      { key: "length", symbolLatex: "l", label: "длина участка", unit: "м", source: "геометрия сети" },
    ],
  },
  {
    id: "thermal_peak_load",
    module: "Thermal",
    title: "Пиковая тепловая нагрузка",
    latex: String.raw`Q_{peak} = \max_t \left(\dot{Q}_{heat}(t)\right)`,
    description: "Максимальная потребная тепловая мощность за рассматриваемый период.",
    methodName: "Максимум временного ряда",
    applicability: "Подбор источника тепла и оценка пикового режима.",
    assumptions: ["Нагрузка берется по расчетному временному ряду"],
    physicalMeaning: "Показывает наибольшую требуемую тепловую мощность в течение расчета.",
    resultMeaning: "Используется при выборе котла, ИТП или другого источника тепла.",
    normReference: "Зональная RC-модель (не норматив СП 50)",
    variables: [
      { key: "q_peak", symbolLatex: "Q_{peak}", label: "пиковая тепловая нагрузка", unit: "кВт", source: "выход" },
      { key: "q_heat_time", symbolLatex: "\\dot{Q}_{heat}(t)", label: "мощность отопления во времени", unit: "кВт", source: "временной ряд" },
    ],
  },
  {
    id: "sp50_kob",
    module: "Thermal",
    title: "Удельная характеристика теплозащиты здания k_ob",
    latex: String.raw`k_{ob} = \frac{\sum n_t A_i / R_{pr,i}}{V_{ot}}`,
    description: "Сводный показатель теплозащиты ограждающих конструкций здания.",
    methodName: "СП 50.13330.2024",
    applicability: "Нормативная проверка теплозащиты здания.",
    assumptions: ["R_pr рассчитаны с учётом неоднородностей", "V_ot — отапливаемый объём"],
    physicalMeaning: "Чем меньше k_ob, тем лучше теплозащита здания.",
    resultMeaning: "Сравнивается с нормативным k_ob^норм.",
    normReference: "СП 50.13330.2024",
    variables: [
      { key: "kob", symbolLatex: "k_{ob}", label: "удельная характеристика", unit: "Вт/(м³·К)", source: "выход" },
      { key: "r_pr", symbolLatex: "R_{pr,i}", label: "приведённое сопротивление фрагмента", unit: "м²·К/Вт", source: "расчёт" },
    ],
  },
  {
    id: "sp50_k_vent",
    module: "Thermal",
    title: "Характеристика теплозащиты вентиляции k_vent",
    latex: String.raw`k_{vent} = \frac{c \left(L_{vent}\gamma n(1-k_{ef}) + G_{inf} n\right)}{168 V_{ot}}`,
    description: "Доля потерь на подогрев приточного и инфильтрационного воздуха в удельной характеристике.",
    methodName: "СП 50.13330.2024",
    applicability: "Расчёт q_от и годовой энергии на отопление.",
    assumptions: ["c = 0,28 кВт·ч/(м³·К)", "L_vent в м³/ч, G_inf в кг/ч"],
    physicalMeaning: "Учитывает механическую вентиляцию и инфильтрацию.",
    resultMeaning: "Входит в q_от = k_ob + k_vent − β(q_быт + q_сол).",
    normReference: "СП 50.13330.2024",
    variables: [
      { key: "k_vent", symbolLatex: "k_{vent}", label: "характеристика вентиляции", unit: "Вт/(м³·К)", source: "выход" },
    ],
  },
  {
    id: "sp50_q_heating",
    module: "Thermal",
    title: "Удельная характеристика расхода теплоты на отопление q_от",
    latex: String.raw`q_{ot} = k_{ob} + k_{vent} - \beta (q_{byt} + q_{sol})`,
    description: "Сводный показатель для сравнения с нормативным удельным расходом.",
    methodName: "СП 50.13330.2024",
    applicability: "Энергетическая характеристика здания.",
    assumptions: ["β — коэффициент использования бытовых и солнечных поступлений"],
    physicalMeaning: "Объединяет потери через ограждение, вентиляцию и вычитает полезные поступления.",
    resultMeaning: "Q_год = 0,024·GSOP·V·q_от.",
    normReference: "СП 50.13330.2024",
    variables: [
      { key: "q_ot", symbolLatex: "q_{ot}", label: "удельная характеристика", unit: "Вт/(м³·К)", source: "выход" },
    ],
  },
  {
    id: "sp50_reduced_r",
    module: "Envelope",
    title: "Приведённое сопротивление теплопередаче R_pr",
    latex: String.raw`R_{pr} = \frac{1}{\sum f_i/R_i + \sum \psi L + \sum \chi n}`,
    description: "Учёт неоднородностей (мостиков холода) в ограждающей конструкции.",
    methodName: "СП 50.13330.2024",
    applicability: "Стены, покрытия, перекрытия с линейными и точечными неоднородностями.",
    assumptions: ["Площадные доли f_i нормированы", "ψ и χ из проекта или справочника"],
    physicalMeaning: "Снижает эффективное сопротивление относительно однородного слоя.",
    resultMeaning: "Используется в k_ob и проверке R ≥ R_норм.",
    normReference: "СП 50.13330.2024",
    variables: [
      { key: "r_pr", symbolLatex: "R_{pr}", label: "приведённое сопротивление", unit: "м²·К/Вт", source: "выход" },
    ],
  },
  {
    id: "rc_infiltration_g",
    module: "Thermal",
    title: "Проводимость инфильтрации в RC-модели",
    latex: String.raw`G_{inf} = \rho c_p V \cdot ACH / 3600`,
    description: "Эквивалентная проводимость воздушного обмена для зональной динамики.",
    methodName: "Чувствительная теплота воздуха",
    applicability: "RC-симуляция Twin Studio.",
    assumptions: ["ρ = 1,204 кг/м³ в RC", "ACH — кратность инфильтрации"],
    physicalMeaning: "Связывает кратность воздухообмена с тепловым потоком к наружной среде.",
    resultMeaning: "Входит в дискретный баланс зоны.",
    normReference: "Инженерная теплофизика (не норматив СП 50)",
    variables: [
      { key: "g_inf", symbolLatex: "G_{inf}", label: "проводимость", unit: "Вт/К", source: "выход" },
    ],
  },
  {
    id: "rc_envelope_loss",
    module: "Thermal",
    title: "Потери через ограждение в диагностическом срезе",
    latex: String.raw`\dot{Q}_{ogr} = \sum_k G_{k,ext} \max(0, T_i - T_n)`,
    description: "Разложение по непрозрачной части, окнам и дверям при T_i > T_n.",
    methodName: "Стационарный срез RC-модели",
    applicability: "Вкладка «Показатели» после solve.",
    assumptions: ["Срез в момент пиковой суммарной мощности отопления"],
    physicalMeaning: "Показывает структуру потерь без нормативного заключения СП 50.",
    resultMeaning: "Доли в круговой/столбчатой диаграмме.",
    normReference: "Q = U·A·ΔT (стационарная теплопередача)",
    variables: [
      { key: "q_env", symbolLatex: "\\dot{Q}_{ogr}", label: "теплопотери ограждения", unit: "Вт", source: "выход" },
    ],
  },
  {
    id: "sensitivity_index",
    module: "Uncertainty",
    title: "Коэффициент чувствительности",
    latex: String.raw`S_x = \frac{\Delta Y / Y}{\Delta X / X}`,
    description: "Локальная чувствительность оценивается конечным возмущением параметра и полным пересчетом результата.",
    methodName: "Локальная чувствительность конечным возмущением",
    applicability: "Сравнение влияния U, ACH, температурного напора и других входов на требуемую мощность.",
    assumptions: ["Изменение параметра мало относительно базовой точки расчета"],
    physicalMeaning: "Показывает, насколько относительное изменение параметра влияет на относительное изменение результата.",
    resultMeaning: "По знаку видно направление влияния, по модулю - его силу.",
    variables: [
      { key: "sensitivity", symbolLatex: "S_x", label: "индекс чувствительности", unit: "безразм.", source: "выход" },
      { key: "input", symbolLatex: "X", label: "входной параметр", source: "вход" },
      { key: "output", symbolLatex: "Y", label: "выходная величина", source: "выход" },
      { key: "delta_input", symbolLatex: "\\Delta X", label: "изменение входного параметра", source: "вариант" },
      { key: "delta_output", symbolLatex: "\\Delta Y", label: "изменение выходной величины", source: "пересчет" },
    ],
  },
  {
    id: "uncertainty_mc",
    module: "Uncertainty",
    title: "Среднее значение по Монте-Карло",
    latex: String.raw`\hat{\mu} = \frac{1}{N}\sum_{k=1}^{N} y_k`,
    description: "Среднее по множеству прогонов при случайных входных параметрах.",
    methodName: "Оценка математического ожидания по выборке",
    applicability: "Анализ неопределенности и вероятностные оценки.",
    assumptions: ["Прогоны независимы", "Выборка репрезентативна"],
    physicalMeaning: "Показывает ожидаемое значение выходной метрики с учетом разброса входов.",
    resultMeaning: "Используется как центральная оценка результата при неопределенности.",
    variables: [
      { key: "samples", symbolLatex: "N", label: "число прогонов", source: "настройки Monte Carlo" },
      { key: "sample_value", symbolLatex: "y_k", label: "результат k-го прогона", source: "выход" },
      { key: "mean_value", symbolLatex: "\\hat{\\mu}", label: "оценка среднего", source: "выход" },
    ],
  },
  {
    id: "uncertainty_std",
    module: "Uncertainty",
    title: "Стандартное отклонение по Монте-Карло",
    latex: String.raw`\hat{\sigma} = \sqrt{\frac{1}{N-1}\sum_{k=1}^{N}(y_k - \hat{\mu})^2}`,
    description: "Оценивает разброс результатов относительно среднего по серии прогонов.",
    methodName: "Несмещенная оценка стандартного отклонения",
    applicability: "Оценка разброса, доверительных интервалов и вероятностных диапазонов.",
    assumptions: ["Выборка достаточно велика для оценки разброса"],
    physicalMeaning: "Показывает степень неопределенности результата.",
    resultMeaning: "Чем больше σ, тем менее устойчив результат к разбросу входных данных.",
    variables: [
      { key: "std_value", symbolLatex: "\\hat{\\sigma}", label: "оценка стандартного отклонения", source: "выход" },
      { key: "mean_value", symbolLatex: "\\hat{\\mu}", label: "среднее значение", source: "выход" },
      { key: "sample_value", symbolLatex: "y_k", label: "результат k-го прогона", source: "выход" },
      { key: "samples", symbolLatex: "N", label: "число прогонов", source: "настройки Monte Carlo" },
    ],
  },
  {
    id: "reduced_resistance_homogeneity",
    module: "Envelope",
    title: "Приведённое сопротивление по коэффициенту однородности",
    latex: String.raw`R_{red} = r \cdot R_0`,
    description: "Приведённое сопротивление учитывает неоднородность конструкции через коэффициент теплотехнической однородности.",
    methodName: "Коэффициент теплотехнической однородности",
    applicability: "Нормативный и диагностический контур проверки ограждений.",
    assumptions: ["Не применять одновременно с явным учётом ψ/χ для той же конструкции", "При отсутствии r принимается r = 1.0 с предупреждением"],
    physicalMeaning: "Снижает эффективное сопротивление относительно однородной конструкции.",
    resultMeaning: "Используется в нормативной проверке, но не добавляется в основной RC-solver как отдельная теплопотеря.",
    contour: "normative-check",
    status: "normative-check",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/formulas.ts", "src/core/thermal/sp50/*"],
    warnings: ["Не суммировать с явным Q_psi для одной и той же конструкции."],
    variables: [
      { key: "r_reduced", symbolLatex: "R_{red}", label: "приведённое сопротивление", unit: "м²·К/Вт", source: "выход" },
      { key: "homogeneity", symbolLatex: "r", label: "коэффициент теплотехнической однородности", source: "проект / допущение" },
      { key: "base_resistance", symbolLatex: "R_0", label: "сопротивление однородной конструкции", unit: "м²·К/Вт", source: "расчёт" },
    ],
  },
  {
    id: "thermal_bridge_linear",
    module: "Envelope",
    title: "Линейные тепловые мосты",
    latex: String.raw`\dot{Q}_{\psi} = \sum_i \psi_i \, l_i \, \Delta T`,
    description: "Теплопотери через линейные мостики холода по коэффициентам ψ и длинам участков.",
    methodName: "Явный учёт линейных мостиков холода",
    applicability: "Derived / normative diagnostics ограждений.",
    assumptions: ["Не применять одновременно с коэффициентом однородности для той же конструкции"],
    physicalMeaning: "Даёт добавочную теплопередачу по линейным неоднородностям.",
    resultMeaning: "Показывается отдельной строкой потерь через мостики холода.",
    contour: "derived-only",
    status: "derived-only",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/formulas.ts", "src/core/thermal/sp50/*"],
    warnings: ["Если уже используется bridgeFactor в physics, не суммировать потери повторно без проверки."],
    variables: [
      { key: "heat_flow", symbolLatex: "\\dot{Q}_{\\psi}", label: "потери через линейные мостики", unit: "Вт", source: "выход" },
      { key: "psi", symbolLatex: "\\psi_i", label: "линейный коэффициент теплопередачи", unit: "Вт/(м·К)", source: "проект / справочник" },
      { key: "length", symbolLatex: "l_i", label: "длина мостика", unit: "м", source: "геометрия модели" },
      { key: "delta_t", symbolLatex: "\\Delta T", label: "перепад температур", unit: "К", source: "расчёт" },
    ],
  },
  {
    id: "thermal_bridge_point",
    module: "Envelope",
    title: "Точечные тепловые мосты",
    latex: String.raw`\dot{Q}_{\chi} = \sum_i \chi_i \, \Delta T`,
    description: "Теплопотери через точечные мостики холода по коэффициентам χ.",
    methodName: "Явный учёт точечных мостиков холода",
    applicability: "Derived / normative diagnostics ограждений.",
    assumptions: ["Не применять одновременно с коэффициентом однородности для той же конструкции"],
    physicalMeaning: "Даёт добавочную теплопередачу по точечным неоднородностям.",
    resultMeaning: "Используется как отдельная строка diagnostics, а не как скрытая часть стен.",
    contour: "derived-only",
    status: "derived-only",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/formulas.ts", "src/core/thermal/sp50/*"],
    variables: [
      { key: "heat_flow", symbolLatex: "\\dot{Q}_{\\chi}", label: "потери через точечные мостики", unit: "Вт", source: "выход" },
      { key: "chi", symbolLatex: "\\chi_i", label: "точечный коэффициент теплопередачи", unit: "Вт/К", source: "проект / справочник" },
      { key: "delta_t", symbolLatex: "\\Delta T", label: "перепад температур", unit: "К", source: "расчёт" },
    ],
  },
  {
    id: "heat_loss_coefficient_total",
    module: "Thermal",
    title: "Суммарный коэффициент теплопотерь",
    latex: String.raw`H = H_{tr} + H_{ve}, \quad H_{tr} = \sum U_i A_i, \quad H_{ve} = \rho c_p L`,
    description: "Сводный коэффициент теплопотерь по ограждениям и воздухообмену.",
    methodName: "Derived heat-loss coefficient",
    applicability: "Derived RC diagnostics, оценка τ и быстрые инженерные проверки.",
    assumptions: ["Не суммировать повторно с уже рассчитанными Q_trans / Q_vent", "Используется только как диагностический показатель"],
    physicalMeaning: "Показывает, сколько ватт теряет здание на каждый кельвин перепада температур.",
    resultMeaning: "Служит входом для оценки тепловой постоянной времени.",
    contour: "derived-only",
    status: "derived-only",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/formulas.ts", "src/core/thermal/derived/metrics.ts"],
    variables: [
      { key: "h_total", symbolLatex: "H", label: "суммарный коэффициент теплопотерь", unit: "Вт/К", source: "выход" },
      { key: "h_transmission", symbolLatex: "H_{tr}", label: "трансмиссионный коэффициент", unit: "Вт/К", source: "расчёт" },
      { key: "h_ventilation", symbolLatex: "H_{ve}", label: "вентиляционный коэффициент", unit: "Вт/К", source: "расчёт" },
    ],
  },
  {
    id: "thermal_time_constant",
    module: "Thermal",
    title: "Тепловая постоянная времени",
    latex: String.raw`\tau = \frac{C}{H}`,
    description: "Оценка инерционности здания или отдельной зоны через отношение теплоёмкости к теплопотерям.",
    methodName: "First-order time constant",
    applicability: "Derived RC diagnostics по зданию и по зонам.",
    assumptions: ["Используется эффективная теплоёмкость RC-модели", "Чем больше τ, тем медленнее здание остывает и нагревается"],
    physicalMeaning: "Характеризует скорость реакции здания на изменение внешних условий.",
    resultMeaning: "Используется для сравнения инерционности зон и свободного остывания.",
    contour: "derived-only",
    status: "derived-only",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/formulas.ts", "src/core/thermal/derived/metrics.ts"],
    variables: [
      { key: "tau", symbolLatex: "\\tau", label: "тепловая постоянная времени", unit: "с или ч", source: "выход" },
      { key: "capacitance", symbolLatex: "C", label: "эффективная теплоёмкость", unit: "Дж/К", source: "RC-модель" },
      { key: "heat_loss_coefficient", symbolLatex: "H", label: "суммарный коэффициент теплопотерь", unit: "Вт/К", source: "derived diagnostics" },
    ],
  },
  {
    id: "free_cooling",
    module: "Thermal",
    title: "Свободное остывание помещения",
    latex: String.raw`T(t) = T_{out} + \left(T_0 - T_{out}\right)e^{-t/\tau}`,
    description: "Приближённый диагностический сценарий отключения отопления без повторного запуска основного solver.",
    methodName: "Экспоненциальное свободное остывание",
    applicability: "Derived-only сценарий free cooling.",
    assumptions: ["Не заменяет основную RC-симуляцию", "Использует ранее рассчитанную τ"],
    physicalMeaning: "Даёт приближённую скорость остывания к наружной температуре.",
    resultMeaning: "Показывает прогноз температуры через 1, 6, 12 и 24 часа без отопления.",
    contour: "derived-only",
    status: "derived-only",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/formulas.ts", "src/core/thermal/derived/metrics.ts"],
    variables: [
      { key: "temperature", symbolLatex: "T(t)", label: "температура в момент времени t", unit: "°C", source: "выход" },
      { key: "initial_temperature", symbolLatex: "T_0", label: "начальная температура", unit: "°C", source: "RC-результат" },
      { key: "outdoor_temperature", symbolLatex: "T_{out}", label: "наружная температура", unit: "°C", source: "сценарий" },
      { key: "tau", symbolLatex: "\\tau", label: "тепловая постоянная времени", unit: "с или ч", source: "derived diagnostics" },
    ],
  },
  {
    id: "internal_surface_temperature",
    module: "Envelope",
    title: "Температура внутренней поверхности",
    latex: String.raw`\Delta t_{si} = n (t_{in} - t_{out}) \frac{R_{si}}{R_0}, \quad \tau_{si} = t_{in} - \Delta t_{si}`,
    description: "Приближённая оценка температуры внутренней поверхности ограждения.",
    methodName: "Проверка поверхности ограждения",
    applicability: "Normative / diagnostic contour ограждений.",
    assumptions: ["Не путать с температурой воздуха помещения из RC-solver"],
    physicalMeaning: "Показывает, насколько поверхность конструкции холоднее воздуха в помещении.",
    resultMeaning: "Используется для оценки холодных поверхностей и риска конденсации.",
    contour: "normative-check",
    status: "normative-check",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/formulas.ts", "src/core/thermal/sp50/*"],
    variables: [
      { key: "surface_temperature", symbolLatex: "\\tau_{si}", label: "температура внутренней поверхности", unit: "°C", source: "выход" },
      { key: "indoor_temperature", symbolLatex: "t_{in}", label: "температура воздуха внутри", unit: "°C", source: "сценарий / норма" },
      { key: "outdoor_temperature", symbolLatex: "t_{out}", label: "наружная температура", unit: "°C", source: "климат" },
      { key: "surface_resistance", symbolLatex: "R_{si}", label: "внутреннее поверхностное сопротивление", unit: "м²·К/Вт", source: "СП / допущение" },
      { key: "total_resistance", symbolLatex: "R_0", label: "полное сопротивление конструкции", unit: "м²·К/Вт", source: "расчёт" },
    ],
  },
  {
    id: "dew_point_magnus",
    module: "Envelope",
    title: "Точка росы по формуле Магнуса",
    latex: String.raw`\gamma(t,\varphi) = \frac{a t}{b + t} + \ln(\varphi), \quad t_{dew} = \frac{b\gamma(t,\varphi)}{a-\gamma(t,\varphi)}`,
    description: "Приближённая оценка температуры точки росы по температуре воздуха и относительной влажности.",
    methodName: "Формула Магнуса",
    applicability: "Проверка поверхностной конденсации.",
    assumptions: ["φ используется в долях единицы", "Проверка носит приближённый характер"],
    physicalMeaning: "Определяет температуру, при которой водяной пар в воздухе достигает насыщения.",
    resultMeaning: "Сравнивается с температурой внутренней поверхности τ_si.",
    contour: "normative-check",
    status: "normative-check",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/formulas.ts", "src/core/thermal/sp50/*"],
    variables: [
      { key: "dew_point", symbolLatex: "t_{dew}", label: "температура точки росы", unit: "°C", source: "выход" },
      { key: "temperature", symbolLatex: "t", label: "температура воздуха", unit: "°C", source: "сценарий" },
      { key: "humidity", symbolLatex: "\\varphi", label: "относительная влажность", unit: "доля единицы", source: "сценарий / допущение" },
    ],
  },
  {
    id: "interstitial_condensation_check",
    module: "Envelope",
    title: "Упрощённая проверка конденсации внутри конструкции",
    latex: String.raw`p_v(x) \le p_{sat}(T(x)), \quad p_v = \varphi \cdot p_{sat}(T)`,
    description: "Optional diagnostic проверки внутренней конденсации по слоям без полноценного влагопереноса.",
    methodName: "Упрощённый влаготехнический контроль",
    applicability: "Только при наличии данных о паропроницаемости слоёв.",
    assumptions: ["Не заявляется как полноценный расчёт влагопереноса", "При отсутствии vapor properties результат не формируется"],
    physicalMeaning: "Сравнивает парциальное давление пара с давлением насыщения вдоль толщины конструкции.",
    resultMeaning: "Если p_v > p_sat(T), возможна внутренняя конденсация.",
    contour: "heuristic",
    status: "heuristic",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/formulas.ts", "src/core/thermal/sp50/*"],
    variables: [
      { key: "vapor_pressure", symbolLatex: "p_v(x)", label: "парциальное давление пара", unit: "Па", source: "расчёт" },
      { key: "saturation_pressure", symbolLatex: "p_{sat}(T(x))", label: "давление насыщения", unit: "Па", source: "расчёт" },
    ],
  },
  {
    id: "temperature_profile_layers",
    module: "Envelope",
    title: "Температурный профиль по толщине конструкции",
    latex: String.raw`q = \frac{t_{in} - t_{out}}{R_0}, \quad T(x) = t_{in} - q \cdot R_x`,
    description: "Расчёт температур на границах слоёв по накопленному сопротивлению.",
    methodName: "Стационарный профиль по сопротивлениям",
    applicability: "Отчёт и diagnostics ограждений.",
    assumptions: ["Одномерный стационарный профиль", "Не CFD и не 3D heatmap"],
    physicalMeaning: "Показывает распределение температуры по толщине многослойной конструкции.",
    resultMeaning: "Используется для графика профиля и проверки точки росы.",
    contour: "normative-check",
    status: "normative-check",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/formulas.ts", "src/core/thermal/sp50/*"],
    variables: [
      { key: "heat_flux", symbolLatex: "q", label: "тепловой поток через конструкцию", unit: "Вт/м²", source: "расчёт" },
      { key: "temperature_at_x", symbolLatex: "T(x)", label: "температура в точке x", unit: "°C", source: "выход" },
      { key: "partial_resistance", symbolLatex: "R_x", label: "накопленное сопротивление до точки x", unit: "м²·К/Вт", source: "расчёт" },
    ],
  },
  {
    id: "fourier_number",
    module: "Thermal",
    title: "Число Фурье для явной схемы 1D",
    latex: String.raw`a = \frac{\lambda}{\rho c}, \quad Fo = \frac{a \Delta t}{\Delta x^2}, \quad Fo \le 0.5`,
    description: "Критерий устойчивости явной конечно-разностной схемы в transient 1D-модуле.",
    methodName: "Критерий устойчивости по числу Фурье",
    applicability: "Только контур transient 1D по слоям конструкции.",
    assumptions: ["Не применять к зональному RC-solver"],
    physicalMeaning: "Показывает соотношение шага по времени и диффузивности тепла в сетке.",
    resultMeaning: "Если Fo > 0.5, явная схема может стать неустойчивой.",
    contour: "transient-1d",
    status: "report-only",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/formulas.ts", "src/core/thermal/transient/*"],
    variables: [
      { key: "diffusivity", symbolLatex: "a", label: "температуропроводность", unit: "м²/с", source: "материал" },
      { key: "fourier", symbolLatex: "Fo", label: "число Фурье", source: "выход" },
      { key: "time_step", symbolLatex: "\\Delta t", label: "шаг по времени", unit: "с", source: "сетка transient" },
      { key: "space_step", symbolLatex: "\\Delta x", label: "пространственный шаг", unit: "м", source: "сетка transient" },
    ],
  },
  {
    id: "heat_equation_1d",
    module: "Thermal",
    title: "Уравнение теплопроводности для слоя",
    latex: String.raw`\rho c \frac{\partial T}{\partial t} = \lambda \frac{\partial^2 T}{\partial x^2}`,
    description: "Базовое дифференциальное уравнение transient 1D-модуля по слоям конструкции.",
    methodName: "Нестационарная теплопроводность",
    applicability: "Formula registry и отчётное пояснение transient-модуля.",
    assumptions: ["Одномерный перенос по толщине слоя"],
    physicalMeaning: "Связывает изменение температуры со временем и кривизной температурного профиля.",
    resultMeaning: "Поясняет физическую основу конечно-разностной схемы transient 1D.",
    contour: "transient-1d",
    status: "report-only",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/transient/*"],
    variables: [
      { key: "density", symbolLatex: "\\rho", label: "плотность материала", unit: "кг/м³", source: "материал" },
      { key: "heat_capacity", symbolLatex: "c", label: "удельная теплоёмкость", unit: "Дж/(кг·К)", source: "материал" },
      { key: "conductivity", symbolLatex: "\\lambda", label: "теплопроводность", unit: "Вт/(м·К)", source: "материал" },
    ],
  },
  {
    id: "boundary_condition_third_kind",
    module: "Thermal",
    title: "Граничные условия третьего рода",
    latex: String.raw`-\lambda \frac{\partial T}{\partial x} = \alpha (T_s - T_{air})`,
    description: "Поверхностный теплообмен между воздухом и поверхностью конструкции.",
    methodName: "Условие Ньютона–Рихмана",
    applicability: "Transient 1D, температурный профиль и пояснение surface resistances.",
    assumptions: ["Используется в пояснении и diagnostics, без изменения физики RC-модели"],
    physicalMeaning: "Связывает плотность теплового потока с разностью температур поверхности и воздуха.",
    resultMeaning: "Поясняет смысл внутренних и наружных поверхностных сопротивлений.",
    contour: "transient-1d",
    status: "report-only",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/transient/*", "src/core/thermal/sp50/*"],
    variables: [
      { key: "conductivity", symbolLatex: "\\lambda", label: "теплопроводность", unit: "Вт/(м·К)", source: "материал" },
      { key: "alpha", symbolLatex: "\\alpha", label: "коэффициент теплоотдачи", unit: "Вт/(м²·К)", source: "СП / допущение" },
      { key: "surface_temperature", symbolLatex: "T_s", label: "температура поверхности", unit: "°C", source: "расчёт" },
      { key: "air_temperature", symbolLatex: "T_{air}", label: "температура воздуха", unit: "°C", source: "сценарий" },
    ],
  },
  {
    id: "normative_ventilation",
    module: "Thermal",
    title: "Нормативный воздухообмен",
    latex: String.raw`L_{required} = \max(L_{people}, L_{area}, L_{room}), \quad L_{people} = n_{people} l_{person}, \quad L_{area} = A l_{area}`,
    description: "Отдельная нормативная проверка воздухообмена без автоматической подмены ACH в solver.",
    methodName: "Normative ventilation check",
    applicability: "СП / эксплуатационная проверка вентиляции.",
    assumptions: ["В основной solver подставляется только при явном флаге режима"],
    physicalMeaning: "Сравнивает заданный расход воздуха с требуемым нормативным расходом.",
    resultMeaning: "Показывает дефицит или избыток воздухообмена и отдельно отмечает влияние на solver.",
    contour: "normative-check",
    status: "normative-check",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/formulas.ts", "src/core/thermal/derived/metrics.ts"],
    variables: [
      { key: "required_flow", symbolLatex: "L_{required}", label: "требуемый расход воздуха", unit: "м³/ч", source: "выход" },
      { key: "people_flow", symbolLatex: "L_{people}", label: "расход по людям", unit: "м³/ч", source: "норма / эксплуатация" },
      { key: "area_flow", symbolLatex: "L_{area}", label: "расход по площади", unit: "м³/ч", source: "норма / геометрия" },
    ],
  },
  {
    id: "ventilation_recovery",
    module: "Thermal",
    title: "Рекуперация вентиляции",
    latex: String.raw`H_{ve,eff} = \rho c_p L (1 - \eta_{rec}), \quad \dot{Q}_{ve,eff} = H_{ve,eff} \Delta T`,
    description: "Derived-only оценка снижения вентиляционных потерь за счёт рекуперации тепла.",
    methodName: "Эффективные потери после рекуперации",
    applicability: "Diagnostics вентиляции и экономической интерпретации.",
    assumptions: ["Не применять дважды, если heatRecoveryFactor уже встроен в другой расчётный контур"],
    physicalMeaning: "Уменьшает потери на подогрев приточного воздуха на долю η_rec.",
    resultMeaning: "Показывает потери до рекуперации, после рекуперации и экономию мощности.",
    contour: "derived-only",
    status: "derived-only",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/formulas.ts", "src/core/thermal/derived/metrics.ts"],
    warnings: ["В текущем RC-контуре показатель показывается как derived-only и не уменьшает solver автоматически."],
    variables: [
      { key: "h_effective", symbolLatex: "H_{ve,eff}", label: "эффективный коэффициент потерь", unit: "Вт/К", source: "выход" },
      { key: "efficiency", symbolLatex: "\\eta_{rec}", label: "КПД рекуперации", unit: "доля", source: "сценарий" },
      { key: "airflow", symbolLatex: "L", label: "расход воздуха", unit: "м³/с", source: "сценарий" },
    ],
  },
  {
    id: "hydronic_heat_capacity",
    module: "Thermal",
    title: "Гидравлическая мощность отопления",
    latex: String.raw`\dot{Q}_{hyd} = \dot{m} c_p (t_{supply} - t_{return}), \quad \dot{m} = \frac{\dot{Q}_{heat}}{c_p (t_{supply} - t_{return})}`,
    description: "Справочный derived-only расчёт требуемого расхода теплоносителя и доступной гидравлической мощности.",
    methodName: "Hydronic reference calculation",
    applicability: "Инженерная оценка оборудования без прямого управления RC-solver.",
    assumptions: ["Если ΔT <= 0, расчёт не выполняется", "Показатель не ограничивает основной RC-solver без отдельного режима"],
    physicalMeaning: "Связывает тепловую мощность с массовым расходом и температурным графиком теплоносителя.",
    resultMeaning: "Используется для подбора расхода и оценки реализуемости пикового теплового запроса.",
    contour: "derived-only",
    status: "derived-only",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/formulas.ts", "src/core/thermal/engineering/*"],
    variables: [
      { key: "hydronic_capacity", symbolLatex: "\\dot{Q}_{hyd}", label: "гидравлическая мощность", unit: "Вт", source: "выход" },
      { key: "mass_flow", symbolLatex: "\\dot{m}", label: "массовый расход теплоносителя", unit: "кг/с", source: "выход" },
      { key: "delta_t", symbolLatex: "t_{supply} - t_{return}", label: "перепад температур теплоносителя", unit: "К", source: "сценарий / допущение" },
    ],
  },
  {
    id: "heating_capacity_limit",
    module: "Thermal",
    title: "Ограничение мощности отопления",
    latex: String.raw`\dot{Q}_{heat,real} = \min(\dot{Q}_{demand}, \dot{Q}_{available})`,
    description: "Отдельный режим capacity-limited heating, в котором solver не догревает зону выше доступной мощности.",
    methodName: "Capacity-limited heating mode",
    applicability: "Только при явном heatingMode = capacityLimited.",
    assumptions: ["Не меняет default ideal-mode", "Должен сопровождаться тестами по unmet load"],
    physicalMeaning: "Ограничивает доступную мощность отопления относительно требуемой.",
    resultMeaning: "Позволяет накапливать unmetLoad и корректно считать дискомфорт при недогреве.",
    contour: "rc-runtime",
    status: "main-runtime",
    affectsSolver: true,
    sourceFiles: ["src/core/thermal/solver.ts", "src/core/thermal/metrics.ts"],
    variables: [
      { key: "heat_real", symbolLatex: "\\dot{Q}_{heat,real}", label: "реальная мощность отопления", unit: "Вт", source: "выход" },
      { key: "heat_demand", symbolLatex: "\\dot{Q}_{demand}", label: "требуемая мощность", unit: "Вт", source: "расчёт" },
      { key: "heat_available", symbolLatex: "\\dot{Q}_{available}", label: "доступная мощность", unit: "Вт", source: "вход режима" },
    ],
  },
  {
    id: "discomfort_hours_split",
    module: "Thermal",
    title: "Часы недогрева и перегрева",
    latex: String.raw`H_{discomfort} = \sum I(T_i < T_{min} \lor T_i > T_{max}) \Delta t, \quad H_{overheat} = \sum I(T_i > T_{max}) \Delta t`,
    description: "Разделение суммарного дискомфорта на часы недогрева и часы перегрева.",
    methodName: "Интеграл индикаторной функции по времени",
    applicability: "Summary metrics RC-расчёта.",
    assumptions: ["Часы могут суммироваться по зонам и быть больше длительности сценария"],
    physicalMeaning: "Показывает, где нарушается комфортная температура и в какую сторону отклоняется режим.",
    resultMeaning: "Используется в summary и diagnostics без изменения самой физики solver.",
    contour: "rc-runtime",
    status: "derived-only",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/metrics.ts", "src/core/thermal/solver.ts"],
    variables: [
      { key: "discomfort_hours", symbolLatex: "H_{discomfort}", label: "суммарные часы дискомфорта", unit: "ч", source: "выход" },
      { key: "overheat_hours", symbolLatex: "H_{overheat}", label: "часы перегрева", unit: "ч", source: "выход" },
    ],
  },
  {
    id: "uncertainty_risk_probability",
    module: "Uncertainty",
    title: "Вероятность риска",
    latex: String.raw`P_{risk} = \frac{N_{fail}}{N}`,
    description: "Доля сценариев Monte Carlo, в которых выполнено условие отказа или превышения порога.",
    methodName: "Эмпирическая вероятность по выборке",
    applicability: "Вероятностный анализ результатов Monte Carlo.",
    assumptions: ["UI только отображает готовые значения и не запускает скрытый Monte Carlo"],
    physicalMeaning: "Показывает вероятность неблагоприятного исхода по ансамблю сценариев.",
    resultMeaning: "Используется для риска недогрева, риска превышения пика и роста энергии.",
    contour: "monte-carlo",
    status: "derived-only",
    affectsSolver: false,
    sourceFiles: ["src/core/uncertainty/thermalMonteCarlo.ts", "src/features/reports/MonteCarloResultsSection.tsx"],
    variables: [
      { key: "risk_probability", symbolLatex: "P_{risk}", label: "вероятность риска", unit: "доля", source: "выход" },
      { key: "fail_count", symbolLatex: "N_{fail}", label: "число неблагоприятных сценариев", source: "выборка Monte Carlo" },
      { key: "samples", symbolLatex: "N", label: "число прогонов", source: "настройки Monte Carlo" },
    ],
  },
  {
    id: "uncertainty_cv",
    module: "Uncertainty",
    title: "Коэффициент вариации Monte Carlo",
    latex: String.raw`CV = \frac{\sigma}{\mu} \cdot 100\%`,
    description: "Относительная мера разброса вероятностного результата по отношению к среднему.",
    methodName: "Coefficient of variation",
    applicability: "Диагностика устойчивости энергии, пика и дискомфорта.",
    assumptions: ["При μ ≈ 0 показатель не определяется корректно"],
    physicalMeaning: "Чем больше CV, тем менее устойчив результат к разбросу входов.",
    resultMeaning: "Используется для инженерной интерпретации неопределённости без нового solver.",
    contour: "monte-carlo",
    status: "derived-only",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/formulas.ts", "src/core/uncertainty/thermalMonteCarlo.ts"],
    variables: [
      { key: "cv", symbolLatex: "CV", label: "коэффициент вариации", unit: "%", source: "выход" },
      { key: "std", symbolLatex: "\\sigma", label: "стандартное отклонение", source: "статистика Monte Carlo" },
      { key: "mean", symbolLatex: "\\mu", label: "среднее значение", source: "статистика Monte Carlo" },
    ],
  },
  {
    id: "uncertainty_confidence_interval",
    module: "Uncertainty",
    title: "Доверительный интервал среднего",
    latex: String.raw`CI_{mean} = \bar{x} \pm z_{\alpha/2}\frac{s}{\sqrt{N}}`,
    description: "Оценка 95%-го доверительного интервала среднего по выборке Monte Carlo.",
    methodName: "Normal-based confidence interval",
    applicability: "Monte Carlo diagnostics и проверка достаточности числа прогонов.",
    assumptions: ["Требует интерпретации как статистической оценки среднего, а не диапазона сценариев"],
    physicalMeaning: "Показывает неопределённость самой оценки среднего по конечной выборке.",
    resultMeaning: "Отделяет разброс сценариев от точности оценки среднего.",
    contour: "monte-carlo",
    status: "report-only",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/formulas.ts", "src/core/uncertainty/thermalMonteCarlo.ts"],
    variables: [
      { key: "ci", symbolLatex: "CI_{mean}", label: "доверительный интервал среднего", source: "выход" },
      { key: "mean", symbolLatex: "\\bar{x}", label: "среднее выборки", source: "статистика Monte Carlo" },
      { key: "std", symbolLatex: "s", label: "стандартное отклонение выборки", source: "статистика Monte Carlo" },
      { key: "samples", symbolLatex: "N", label: "число прогонов", source: "настройки Monte Carlo" },
    ],
  },
  {
    id: "uncertainty_corr_sensitivity",
    module: "Uncertainty",
    title: "Чувствительность по корреляции",
    latex: String.raw`S_i \approx \left|\mathrm{corr}(X_i, Y)\right|`,
    description: "Текущий sensitivity method label в Monte Carlo основан на абсолютной нормированной корреляции факторов с totalEnergyKWh.",
    methodName: "Pearson correlation (absolute normalized)",
    applicability: "Текущий основной probabilistic workflow.",
    assumptions: ["Это не Morris и не Sobol", "Используется готовая выборка без отдельной схемы отбора"],
    physicalMeaning: "Оценивает тесноту связи изменения входного параметра с итоговой метрикой.",
    resultMeaning: "Позволяет ранжировать факторы по влиянию на итоговую энергию отопления.",
    contour: "monte-carlo",
    status: "derived-only",
    affectsSolver: false,
    sourceFiles: ["src/core/uncertainty/thermalMonteCarlo.ts", "src/features/reports/MonteCarloResultsSection.tsx"],
    variables: [
      { key: "sensitivity", symbolLatex: "S_i", label: "показатель чувствительности", source: "выход" },
      { key: "input", symbolLatex: "X_i", label: "входной фактор", source: "сценарий Monte Carlo" },
      { key: "output", symbolLatex: "Y", label: "итоговая метрика", source: "scenarioSeries.totalEnergyKWh" },
    ],
  },
  {
    id: "specific_heat_load_area",
    module: "Thermal",
    title: "Удельная тепловая нагрузка по площади",
    latex: String.raw`q_A = \frac{\dot{Q}_{heat}}{A_{floor}}`,
    description: "Derived удельная нагрузка на единицу площади пола модели.",
    methodName: "Specific load by floor area",
    applicability: "Diagnostics результатов RC-расчёта.",
    assumptions: ["Используется реальная площадь модели, а не placeholder деления на 100"],
    physicalMeaning: "Показывает плотность тепловой нагрузки по площади.",
    resultMeaning: "Применяется для сравнения зон и сценариев между собой.",
    contour: "derived-only",
    status: "derived-only",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/formulas.ts", "src/core/thermal/derived/metrics.ts"],
    variables: [
      { key: "specific_load", symbolLatex: "q_A", label: "удельная нагрузка", unit: "Вт/м²", source: "выход" },
      { key: "heat_flow", symbolLatex: "\\dot{Q}_{heat}", label: "тепловая мощность отопления", unit: "Вт", source: "RC summary" },
      { key: "floor_area", symbolLatex: "A_{floor}", label: "площадь пола", unit: "м²", source: "геометрия модели" },
    ],
  },
  {
    id: "specific_heat_load_volume",
    module: "Thermal",
    title: "Удельная тепловая нагрузка по объёму",
    latex: String.raw`q_V = \frac{\dot{Q}_{heat}}{V}, \quad q_{V\Delta T} = \frac{\dot{Q}_{heat}}{V \Delta T}`,
    description: "Derived удельные показатели по объёму здания и объёму с температурным напором.",
    methodName: "Specific load by volume",
    applicability: "Diagnostics результатов RC-расчёта.",
    assumptions: ["Не рассчитывается при V = 0 или при отсутствии корректного ΔT"],
    physicalMeaning: "Позволяет сравнивать нагрузку на единицу объёма и нормировать её по температурному напору.",
    resultMeaning: "Используется как вспомогательная инженерная метрика качества оболочки и сценария.",
    contour: "derived-only",
    status: "derived-only",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/formulas.ts", "src/core/thermal/derived/metrics.ts"],
    variables: [
      { key: "specific_volume_load", symbolLatex: "q_V", label: "удельная нагрузка по объёму", unit: "Вт/м³", source: "выход" },
      { key: "specific_volume_delta_t_load", symbolLatex: "q_{V\\Delta T}", label: "удельная нагрузка по объёму и ΔT", unit: "Вт/(м³·К)", source: "выход" },
      { key: "volume", symbolLatex: "V", label: "объём модели", unit: "м³", source: "геометрия модели" },
    ],
  },
  {
    id: "calibration_rmse",
    module: "Calibration",
    title: "RMSE по месячным данным",
    latex: String.raw`RMSE = \sqrt{\frac{1}{M}\sum_{m=1}^{M}(E_m^{obs} - E_m^{sim})^2}`,
    description: "Классическая метрика расхождения между наблюдаемыми и расчетными месячными энергозатратами.",
    methodName: "Root Mean Square Error",
    applicability: "Калибровка модели по 12 месячным значениям или другой серии наблюдений.",
    assumptions: ["Все наблюдения даны в одинаковых единицах", "Каждая точка имеет одинаковый вес, если не задано иное"],
    physicalMeaning: "Показывает средний масштаб ошибки модели в тех же единицах, что и энергия.",
    resultMeaning: "Меньший RMSE означает лучшее совпадение модели с наблюдениями.",
    variables: [
      { key: "observations", symbolLatex: "M", label: "число наблюдений", source: "данные калибровки" },
      { key: "energy_obs", symbolLatex: "E_m^{obs}", label: "наблюдаемая энергия", unit: "кВт·ч", source: "измерения" },
      { key: "energy_sim", symbolLatex: "E_m^{sim}", label: "расчетная энергия", unit: "кВт·ч", source: "модель" },
    ],
  },
  {
    id: "calibration_mape",
    module: "Calibration",
    title: "MAPE по месячным данным",
    latex: String.raw`MAPE = \frac{100\%}{M}\sum_{m=1}^{M}\left|\frac{E_m^{obs} - E_m^{sim}}{E_m^{obs}}\right|`,
    description: "Средняя относительная ошибка между расчетом и наблюдениями в процентах.",
    methodName: "Mean Absolute Percentage Error",
    applicability: "Сравнение качества калибровки в относительных единицах.",
    assumptions: ["Наблюдаемые значения не равны нулю", "Все точки имеют одинаковый вес, если не задано иное"],
    physicalMeaning: "Показывает типичную относительную ошибку модели.",
    resultMeaning: "Чем меньше MAPE, тем ближе модель к фактическим месячным данным.",
    variables: [
      { key: "observations", symbolLatex: "M", label: "число наблюдений", source: "данные калибровки" },
      { key: "energy_obs", symbolLatex: "E_m^{obs}", label: "наблюдаемая энергия", unit: "кВт·ч", source: "измерения" },
      { key: "energy_sim", symbolLatex: "E_m^{sim}", label: "расчетная энергия", unit: "кВт·ч", source: "модель" },
    ],
  },
  {
    id: "derived_compactness",
    module: "Thermal",
    title: "Коэффициент компактности здания",
    titleRu: "Коэффициент компактности здания",
    latex: String.raw`K_{compact} = \frac{A_{env}}{V_h}`,
    formulaLatex: String.raw`K_{compact} = \frac{A_{env}}{V_h}`,
    description: "Отношение площади наружной оболочки к отапливаемому объёму.",
    methodName: "Derived building performance",
    applicability: "Диагностика формы здания; не влияет на RC-solver.",
    assumptions: ["A_env — только наружная оболочка", "V_h > 0"],
    physicalMeaning: "Характеризует компактность теплооболочки.",
    resultMeaning: "Derived-only показатель для отчёта и сравнения вариантов.",
    contour: "derived-only",
    status: "derived-only",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/derived/buildingPerformanceMetrics.ts"],
    warnings: ["При V_h <= 0 значение не рассчитывается."],
    variables: [
      { key: "A_env", symbolLatex: "A_{env}", label: "площадь наружной оболочки", unit: "м²" },
      { key: "V_h", symbolLatex: "V_h", label: "отапливаемый объём", unit: "м³" },
    ],
  },
  {
    id: "derived_wwr",
    module: "Thermal",
    title: "Доля остекления фасада",
    titleRu: "Доля остекления фасада",
    latex: String.raw`WWR = \frac{A_{win}}{A_{facade}}`,
    formulaLatex: String.raw`WWR = \frac{A_{win}}{A_{facade}}`,
    description: "Отношение площади окон к площади наружных фасадов.",
    methodName: "Derived building performance",
    applicability: "Диагностика ограждающих конструкций.",
    assumptions: ["A_facade > 0"],
    physicalMeaning: "Характеризует прозрачность фасада.",
    resultMeaning: "Derived-only; дополнительно показывается WWR в процентах.",
    contour: "derived-only",
    status: "derived-only",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/derived/buildingPerformanceMetrics.ts"],
    variables: [
      { key: "A_win", symbolLatex: "A_{win}", label: "площадь окон", unit: "м²" },
      { key: "A_facade", symbolLatex: "A_{facade}", label: "площадь фасада", unit: "м²" },
    ],
  },
  {
    id: "derived_u_eq",
    module: "Thermal",
    title: "Эквивалентный коэффициент теплопередачи",
    titleRu: "Эквивалентный коэффициент теплопередачи оболочки",
    latex: String.raw`U_{eq} = \frac{\sum U_i A_i}{\sum A_i}`,
    formulaLatex: String.raw`U_{eq} = \frac{\sum U_i A_i}{\sum A_i}`,
    description: "Площадно-взвешенный U по элементам ограждения.",
    methodName: "Derived building performance",
    applicability: "Элементы с валидными U и A.",
    assumptions: ["Не смешивать R_red с ψ/χ для одного элемента"],
    physicalMeaning: "Сводный U оболочки.",
    resultMeaning: "Derived-only диагностика.",
    contour: "derived-only",
    status: "derived-only",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/derived/buildingPerformanceMetrics.ts"],
    variables: [
      { key: "U_i", symbolLatex: "U_i", label: "U элемента", unit: "Вт/(м²·К)" },
      { key: "A_i", symbolLatex: "A_i", label: "площадь элемента", unit: "м²" },
    ],
  },
  {
    id: "derived_h_total",
    module: "Thermal",
    title: "Общий коэффициент теплопотерь",
    titleRu: "Общий коэффициент теплопотерь",
    latex: String.raw`H_{total} = H_{tr} + H_{ve} + H_{\psi} + H_{\chi}`,
    formulaLatex: String.raw`H_{total} = H_{tr} + H_{ve} + H_{\psi} + H_{\chi}`,
    description: "Сумма трансмиссионных, вентиляционных и мостиковых составляющих.",
    methodName: "Derived building performance",
    applicability: "Диагностика теплопотерь здания.",
    assumptions: ["H_ψ и H_χ только при явно заданных мостиках", "H_ve включает инфильтрацию и вентиляцию"],
    physicalMeaning: "Сводный коэффициент теплопотерь, Вт/К.",
    resultMeaning: "Derived-only; breakdown по компонентам.",
    contour: "derived-only",
    status: "derived-only",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/derived/buildingPerformanceMetrics.ts"],
    variables: [
      { key: "H_tr", symbolLatex: "H_{tr}", label: "трансмиссия", unit: "Вт/К" },
      { key: "H_ve", symbolLatex: "H_{ve}", label: "воздухообмен", unit: "Вт/К" },
      { key: "H_psi", symbolLatex: "H_{\psi}", label: "линейные мостики", unit: "Вт/К" },
      { key: "H_chi", symbolLatex: "H_{\chi}", label: "точечные мостики", unit: "Вт/К" },
    ],
  },
  {
    id: "derived_dh_underheat",
    module: "Thermal",
    title: "Градусо-часы недогрева",
    titleRu: "Градусо-часы недогрева",
    latex: String.raw`DH_{underheat} = \sum \max(0, T_{min} - T_{in}(t)) \cdot \Delta t`,
    formulaLatex: String.raw`DH_{underheat} = \sum \max(0, T_{min} - T_{in}(t)) \cdot \Delta t`,
    description: "Интеграл недогрева относительно T_min по временному ряду.",
    methodName: "Derived comfort metrics",
    applicability: "Наличие timeline RC-расчёта.",
    assumptions: ["T_min из comfort settings или setpoints"],
    physicalMeaning: "Показатель недогрева, °C·ч.",
    resultMeaning: "Derived-only; отличается от discomfortHours.",
    contour: "derived-only",
    status: "derived-only",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/derived/buildingPerformanceMetrics.ts"],
    variables: [
      { key: "T_min", symbolLatex: "T_{min}", label: "минимальная допустимая температура", unit: "°C" },
      { key: "T_in", symbolLatex: "T_{in}(t)", label: "температура воздуха", unit: "°C" },
    ],
  },
  {
    id: "derived_dh_overheat",
    module: "Thermal",
    title: "Градусо-часы перегрева",
    titleRu: "Градусо-часы перегрева",
    latex: String.raw`DH_{overheat} = \sum \max(0, T_{in}(t) - T_{max}) \cdot \Delta t`,
    formulaLatex: String.raw`DH_{overheat} = \sum \max(0, T_{in}(t) - T_{max}) \cdot \Delta t`,
    description: "Интеграл перегрева относительно T_max.",
    methodName: "Derived comfort metrics",
    applicability: "Наличие timeline RC-расчёта.",
    assumptions: ["T_max из comfort settings или default 26 °C с warning"],
    physicalMeaning: "Показатель перегрева, °C·ч.",
    resultMeaning: "Derived-only.",
    contour: "derived-only",
    status: "derived-only",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/derived/buildingPerformanceMetrics.ts"],
    variables: [
      { key: "T_max", symbolLatex: "T_{max}", label: "максимальная допустимая температура", unit: "°C" },
    ],
  },
  {
    id: "derived_t_op",
    module: "Thermal",
    title: "Оперативная температура",
    titleRu: "Оперативная температура",
    latex: String.raw`T_{op} = \frac{T_{air} + T_{mrt}}{2}`,
    formulaLatex: String.raw`T_{op} = \frac{T_{air} + T_{mrt}}{2}`,
    description: "Среднее между температурой воздуха и средней радиационной температурой.",
    methodName: "Derived comfort metrics",
    applicability: "При наличии T_mrt или оценки по поверхностям с warning.",
    assumptions: ["T_mrt не заменяется T_air без предупреждения"],
    physicalMeaning: "Показатель теплового комфорта.",
    resultMeaning: "Derived-only по помещениям.",
    contour: "derived-only",
    status: "derived-only",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/derived/buildingPerformanceMetrics.ts"],
    variables: [
      { key: "T_air", symbolLatex: "T_{air}", label: "температура воздуха", unit: "°C" },
      { key: "T_mrt", symbolLatex: "T_{mrt}", label: "средняя радиационная температура", unit: "°C" },
    ],
  },
  {
    id: "derived_f_rsi",
    module: "Thermal",
    title: "Температурный фактор внутренней поверхности",
    titleRu: "Температурный фактор внутренней поверхности",
    latex: String.raw`f_{Rsi} = \frac{\tau_{si} - T_{out}}{T_{in} - T_{out}}`,
    formulaLatex: String.raw`f_{Rsi} = \frac{\tau_{si} - T_{out}}{T_{in} - T_{out}}`,
    description: "Диагностика риска холодных поверхностей.",
    methodName: "Derived comfort metrics",
    applicability: "T_in ≠ T_out; τ_si из surface diagnostics.",
    assumptions: ["Не заменяет расчёт влагопереноса"],
    physicalMeaning: "Безразмерный фактор f_Rsi.",
    resultMeaning: "Статус: normal / cold_surface_risk / mold_risk_possible.",
    contour: "derived-only",
    status: "derived-only",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/derived/buildingPerformanceMetrics.ts"],
    variables: [
      { key: "tau_si", symbolLatex: "\\tau_{si}", label: "температура внутренней поверхности", unit: "°C" },
    ],
  },
  {
    id: "derived_q_pipe",
    module: "Thermal",
    title: "Теплопотери трубопровода",
    titleRu: "Теплопотери трубопровода",
    latex: String.raw`Q_{pipe} = U_{pipe} \cdot L \cdot (T_{water} - T_{air})`,
    formulaLatex: String.raw`Q_{pipe} = U_{pipe} \cdot L \cdot (T_{water} - T_{air})`,
    description: "Линейные теплопотери трубы.",
    methodName: "Derived networks",
    applicability: "U_pipe, L и T_water известны.",
    assumptions: ["derived-only; не меняет RC-solver"],
    physicalMeaning: "Мощность потерь, Вт.",
    resultMeaning: "Q_pipe_gain_to_room для труб внутри помещения.",
    contour: "derived-only",
    status: "derived-only",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/derived/buildingPerformanceMetrics.ts"],
    variables: [
      { key: "U_pipe", symbolLatex: "U_{pipe}", label: "линейный U", unit: "Вт/(м·К)" },
      { key: "L", symbolLatex: "L", label: "длина", unit: "м" },
    ],
  },
  {
    id: "derived_co2",
    module: "Thermal",
    title: "Углеродный след",
    titleRu: "Углеродный след",
    latex: String.raw`CO_2 = E \cdot EF`,
    formulaLatex: String.raw`CO_2 = E \cdot EF`,
    description: "Выбросы CO₂ от потреблённой энергии.",
    methodName: "Derived ecology",
    applicability: "Заданы E и emissionFactor.",
    assumptions: ["E из totalEnergyKWh или annualEnergyKWh с подписью источника"],
    physicalMeaning: "Масса CO₂, кг.",
    resultMeaning: "Derived-only; также CO₂ в тоннах.",
    contour: "derived-only",
    status: "derived-only",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/derived/buildingPerformanceMetrics.ts"],
    variables: [
      { key: "E", symbolLatex: "E", label: "энергия", unit: "кВт·ч" },
      { key: "EF", symbolLatex: "EF", label: "коэффициент выбросов", unit: "кг CO₂/(кВт·ч)" },
    ],
  },
  {
    id: "derived_validation_mbe",
    module: "Calibration",
    title: "MBE валидации цифрового двойника",
    titleRu: "MBE валидации цифрового двойника",
    latex: String.raw`MBE = \frac{\sum (M_i - S_i)}{\sum M_i} \cdot 100\%`,
    formulaLatex: String.raw`MBE = \frac{\sum (M_i - S_i)}{\sum M_i} \cdot 100\%`,
    description: "Mean Bias Error между измерениями и моделью.",
    methodName: "Twin validation",
    applicability: "Синхронизированные measured/simulated series.",
    assumptions: ["Не генерируются синтетические measured data"],
    physicalMeaning: "Систематическое смещение модели, %.",
    resultMeaning: "Derived-only валидация.",
    contour: "derived-only",
    status: "derived-only",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/derived/buildingPerformanceMetrics.ts"],
    variables: [
      { key: "M_i", symbolLatex: "M_i", label: "измеренное значение" },
      { key: "S_i", symbolLatex: "S_i", label: "смоделированное значение" },
    ],
  },
  {
    id: "derived_validation_cvrmse",
    module: "Calibration",
    title: "CVRMSE валидации",
    titleRu: "CVRMSE валидации цифрового двойника",
    latex: String.raw`CVRMSE = \frac{\sqrt{\sum (M_i - S_i)^2 / (n-1)}}{mean(M)} \cdot 100\%`,
    formulaLatex: String.raw`CVRMSE = \frac{\sqrt{\sum (M_i - S_i)^2 / (n-1)}}{mean(M)} \cdot 100\%`,
    description: "Коэффициент вариации RMSE.",
    methodName: "Twin validation",
    applicability: "n ≥ 2 синхронизированных точек.",
    assumptions: ["mean(M) ≠ 0"],
    physicalMeaning: "Относительная ошибка модели, %.",
    resultMeaning: "Derived-only.",
    contour: "derived-only",
    status: "derived-only",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/derived/buildingPerformanceMetrics.ts"],
    variables: [],
  },
  {
    id: "derived_validation_rmse",
    module: "Calibration",
    title: "RMSE_T валидации",
    titleRu: "RMSE_T валидации цифрового двойника",
    latex: String.raw`RMSE_T = \sqrt{\frac{\sum (T_{meas,i} - T_{sim,i})^2}{N}}`,
    formulaLatex: String.raw`RMSE_T = \sqrt{\frac{\sum (T_{meas,i} - T_{sim,i})^2}{N}}`,
    description: "Среднеквадратичная ошибка температуры.",
    methodName: "Twin validation",
    applicability: "Синхронизированные температурные ряды.",
    assumptions: ["Безопасное сопоставление по timestamp при разной длине"],
    physicalMeaning: "RMSE, °C.",
    resultMeaning: "Derived-only.",
    contour: "derived-only",
    status: "derived-only",
    affectsSolver: false,
    sourceFiles: ["src/core/thermal/derived/buildingPerformanceMetrics.ts"],
    variables: [],
  },
];

export const groupedFormulas: Record<FormulaModule, Formula[]> = formulaModules.reduce((acc, module) => {
  acc[module] = formulaRegistry.filter((formula) => formula.module === module);
  return acc;
}, {} as Record<FormulaModule, Formula[]>);

export const formulaMap: Record<string, Formula> = formulaRegistry.reduce(
  (acc, formula) => ({
    ...acc,
    [formula.id]: formula,
  }),
  {} as Record<string, Formula>
);

export const assumptions: Assumption[] = [
  {
    id: "air_density",
    label: "Плотность воздуха",
    value: "1.204",
    unit: "кг/м³",
    description: "Используется в формулах вентиляционных и инфильтрационных потерь.",
    source: "Исаченко В.П., Осипова В.А., Сукомел А.С. «Теплопередача»; инженерное допущение для сухого воздуха около 20 °C",
  },
  {
    id: "air_cp",
    label: "Удельная теплоемкость воздуха",
    value: "1005",
    unit: "Дж/(кг·К)",
    description: "Используется для расчета чувствительной теплоты воздуха.",
    source: "Исаченко В.П., Осипова В.А., Сукомел А.С. «Теплопередача»; инженерное допущение для сухого воздуха около 20 °C",
  },
  {
    id: "air_heat_capacity_bulk",
    label: "Объемная теплоемкость воздуха",
    value: "1.21",
    unit: "кДж/(м³·К)",
    description: "Приближенное произведение плотности воздуха на его теплоемкость.",
    source: "Производная инженерная величина из ρ и c_p воздуха",
  },
  {
    id: "surface_resistance_internal",
    label: "Внутреннее поверхностное сопротивление",
    value: "0.13",
    unit: "м²·К/Вт",
    description: "Типовое сопротивление теплоотдаче со стороны помещения.",
    source: "СП 50.13330.2024, табличные значения коэффициентов теплоотдачи / поверхностных сопротивлений",
  },
  {
    id: "surface_resistance_external",
    label: "Наружное поверхностное сопротивление",
    value: "0.04",
    unit: "м²·К/Вт",
    description: "Типовое сопротивление теплоотдаче со стороны наружного воздуха.",
    source: "СП 50.13330.2024, табличные значения коэффициентов теплоотдачи / поверхностных сопротивлений",
  },
  {
    id: "comfort_setpoint_day",
    label: "Дневная уставка температуры",
    value: "21",
    unit: "°C",
    description: "Базовая дневная температура в расчетах по умолчанию.",
    source: "Настройки приложения",
  },
  {
    id: "comfort_setpoint_night",
    label: "Ночная уставка температуры",
    value: "18",
    unit: "°C",
    description: "Базовая ночная температура в расчетах по умолчанию.",
    source: "Настройки приложения",
  },
];

export const getFormulasByIds = (ids: string[]): Formula[] => ids.map((id) => formulaMap[id]).filter(Boolean);
