export interface MetricInfoDefinition {
  title: string;
  meaning: string;
  formula?: string;
  inputs?: string | string[];
  calculatedIn?: string;
  notes?: string | string[];
}

export const resultsMetricInfo = {
  energy: {
    title: "Энергия отопления",
    meaning: "Интеграл суммарной мощности отопления по всем помещениям за расчётный период.",
    formula: "E = Σ_t Σ_z Q_heat,z(t) · Δt / 3 600 000",
    inputs: ["Q_heat,z(t)", "Δt", "временные ряды зон RC-модели"],
    calculatedIn: "src/core/thermal/solver.ts → runThermalSimulation(...).summary.totalEnergyKWh",
  },
  peakLoad: {
    title: "Пиковая нагрузка",
    meaning: "Максимум по времени суммы требуемой мощности отопления по зонам.",
    formula: "Q_peak = max_t Σ_z Q_heat,z(t)",
    inputs: ["Q_heat,z(t)", "временной шаг RC-модели"],
    calculatedIn: "src/core/thermal/solver.ts → runThermalSimulation(...).summary.peakLoadKW",
  },
  discomfort: {
    title: "Часы дискомфорта",
    meaning: "Сумма часов, когда температура в зоне оказалась ниже уставки больше чем на 0,05 °C.",
    formula: "H = Σ_t Σ_z I(T_z(t) + 0.05 < T_set,z(t)) · Δt / 3600",
    inputs: ["T_z(t)", "T_set,z(t)", "Δt"],
    calculatedIn: "src/core/thermal/solver.ts → runThermalSimulation(...).summary.discomfortHours",
  },
  rcBalance: {
    title: "Нестационарный RC-баланс",
    meaning: "Базовое дифференциальное уравнение зонального нестационарного расчёта.",
    formula: "C · ΔT/Δt = ΣG(T_neighbor − T_zone) + G_inf(T_out − T_zone) + Q_int + Q_heat",
    inputs: [
      "теплоёмкость зоны C",
      "связи G",
      "инфильтрация",
      "наружная температура",
      "внутренние теплопоступления",
      "догрев",
    ],
    calculatedIn: "src/core/thermal/solver.ts → simulateThermalNetwork(...)",
    notes: "Monte Carlo в проекте — это многократный запуск этой же RC-модели с вариацией входных данных.",
  },
  heatLossCoefficientTransmission: {
    title: "Трансмиссионный коэффициент теплопотерь",
    meaning: "Сводный коэффициент потерь через ограждения H_tr по текущей RC-модели.",
    formula: "H_tr = Σ U_i · A_i",
    inputs: ["conductance внешних связей RC-модели"],
    calculatedIn: "src/core/thermal/derived/metrics.ts → transmissionHeatLossCoefficient_W_K",
  },
  heatLossCoefficientVentilation: {
    title: "Коэффициент потерь на воздухообмен",
    meaning: "Суммарный коэффициент потерь на вентиляцию и/или вентиляцию после рекуперации.",
    formula: "H_ve = ρ · c_p · L",
    inputs: ["ventilation conductance RC-модели", "heatRecoveryFactor"],
    calculatedIn: "src/core/thermal/derived/metrics.ts → ventilationHeatLossCoefficient_W_K",
    notes: "Если heatRecoveryFactor > 0, в derived diagnostics показывается H_ve,eff и предупреждение, что solver не уменьшается автоматически.",
  },
  heatLossCoefficientTotal: {
    title: "Суммарный коэффициент теплопотерь",
    meaning: "Общий derived-показатель потерь здания на 1 К перепада температур.",
    formula: "H = H_tr + H_inf + H_ve",
    inputs: ["H_tr", "H_inf", "H_ve"],
    calculatedIn: "src/core/thermal/derived/metrics.ts → totalHeatLossCoefficient_W_K",
  },
  thermalTimeConstant: {
    title: "Тепловая постоянная времени",
    meaning: "Показывает инерционность здания или помещения.",
    formula: "τ = C / H",
    inputs: ["эффективная теплоёмкость C", "суммарный коэффициент потерь H"],
    calculatedIn: "src/core/thermal/derived/metrics.ts → buildingTauHours / zoneTauHours",
    notes: "Чем больше τ, тем медленнее здание остывает и нагревается.",
  },
  freeCooling: {
    title: "Свободное остывание",
    meaning: "Приближённый прогноз температуры без отопления по ранее рассчитанной τ.",
    formula: "T(t) = T_out + (T_0 − T_out) · exp(−t / τ)",
    inputs: ["T_0", "T_out", "τ"],
    calculatedIn: "src/core/thermal/derived/metrics.ts → freeCooling",
    notes: "Это отдельный derived-сценарий, который не заменяет основной RC-расчёт.",
  },
  specificLoadArea: {
    title: "Удельная нагрузка по площади",
    meaning: "Derived-плотность тепловой нагрузки на единицу площади пола.",
    formula: "q_A = Q_heat / A_floor",
    inputs: ["Q_heat", "A_floor"],
    calculatedIn: "src/core/thermal/derived/metrics.ts → specificIndicators.qArea_W_m2",
  },
  specificLoadVolume: {
    title: "Удельная нагрузка по объёму",
    meaning: "Derived-плотность тепловой нагрузки на единицу объёма и объёма с температурным напором.",
    formula: "q_V = Q_heat / V; q_VΔT = Q_heat / (V · ΔT)",
    inputs: ["Q_heat", "V", "ΔT"],
    calculatedIn: "src/core/thermal/derived/metrics.ts → specificIndicators.qVolume_W_m3 / qVolumeDeltaT_W_m3K",
  },
  ventilationRecovery: {
    title: "Рекуперация вентиляции",
    meaning: "Derived-only оценка потерь до и после рекуперации по текущему heatRecoveryFactor.",
    formula: "H_ve,eff = ρ · c_p · L · (1 − η_rec)",
    inputs: ["L", "η_rec", "ΔT"],
    calculatedIn: "src/core/thermal/derived/metrics.ts → ventilationRecovery",
    notes: "Если основной solver пока не учитывает рекуперацию напрямую, блок показывает это предупреждением.",
  },
  monteCarloP10: {
    title: "Медиана снизу (P10)",
    meaning: "Значение, ниже которого находится 10% сценариев вероятностного расчёта.",
    formula: "P10 = quantile(totalEnergyKWh, 0.10)",
    inputs: "scenarioSeries.totalEnergyKWh",
    calculatedIn: "src/core/uncertainty/thermalMonteCarlo.ts → totalEnergy.p10",
  },
  monteCarloP50: {
    title: "Медиана Monte Carlo (P50)",
    meaning: "Медианное значение по всем сценариям вероятностного расчёта.",
    formula: "P50 = quantile(totalEnergyKWh, 0.50)",
    inputs: "scenarioSeries.totalEnergyKWh",
    calculatedIn: "src/core/uncertainty/thermalMonteCarlo.ts → totalEnergy.p50",
  },
  monteCarloP90: {
    title: "Медиана сверху (P90)",
    meaning: "Значение, ниже которого находится 90% сценариев вероятностного расчёта.",
    formula: "P90 = quantile(totalEnergyKWh, 0.90)",
    inputs: "scenarioSeries.totalEnergyKWh",
    calculatedIn: "src/core/uncertainty/thermalMonteCarlo.ts → totalEnergy.p90",
  },
  monteCarloHistogram: {
    title: "Гистограмма Monte Carlo",
    meaning: "Распределение totalEnergyKWh по всем вероятностным сценариям.",
    formula: "binCount_i = count(totalEnergyKWh ∈ bin_i)",
    inputs: ["scenarioSeries.totalEnergyKWh", "histogram bins"],
    calculatedIn: "src/core/uncertainty/thermalMonteCarlo.ts → totalEnergy.histogram",
  },
  coefficientOfVariation: {
    title: "Коэффициент вариации",
    meaning: "Относительная мера разброса результатов Monte Carlo по отношению к среднему значению показателя.",
    formula: "CV = σ / μ · 100%",
    inputs: ["mean", "stdDev"],
    calculatedIn: "Results → Вероятностный анализ → производная метрика по DistributionSummary",
    notes: ["<10% — устойчивый результат", "10–25% — умеренная неопределённость", ">25% — высокая неопределённость"],
  },
  probabilisticSpread: {
    title: "Ширина диапазона P10–P90",
    meaning: "Показывает диапазон, внутри которого находится основная часть вероятностных сценариев.",
    formula: "ΔP = P90 − P10",
    inputs: ["p10", "p90"],
    calculatedIn: "Results → Вероятностный анализ → производная метрика по DistributionSummary",
    notes: "Относительная ширина считается как ΔP_rel = (P90 − P10) / P50 · 100%.",
  },
  exceedanceProbability: {
    title: "Вероятность превышения порога",
    meaning: "Доля сценариев, в которых показатель превысил заданный инженерный порог.",
    formula: "P_exceed = count(Y > Y_lim) / N",
    inputs: ["scenarioSeries", "Y_lim", "число сценариев N"],
    calculatedIn: "Results → Вероятностный анализ → probabilityOf(...)",
  },
  energyGrowthRisk: {
    title: "Риск роста энергии",
    meaning: "Вероятность того, что энергия отопления в сценарии Monte Carlo превысит базовый результат на 20%.",
    formula: "P = count(E_i > 1.2 · E_base) / N",
    inputs: ["scenarioSeries.totalEnergyKWh", "baseResult.summary.totalEnergyKWh"],
    calculatedIn: "Results → Вероятностный анализ → probabilityOf(...)",
  },
  stabilityIndex: {
    title: "Индекс устойчивости теплового режима",
    meaning: "Показывает, какая доля сценариев проходит без риска недогрева ниже принятого температурного порога.",
    formula: "R = (1 − P_underheat) · 100%",
    inputs: ["underheatingBelow20CProbability"],
    calculatedIn: "Results → Вероятностный анализ → производная метрика по Monte Carlo risk",
    notes: [">90% — устойчивый режим", "70–90% — требуется проверка", "<70% — высокий риск"],
  },
  sensitivity: {
    title: "Чувствительность факторов",
    meaning: "Оценка вклада входного фактора в разброс выбранной целевой метрики по результатам Monte Carlo.",
    formula: "S_i = normalized influence(input_i → targetMetric)",
    inputs: ["samples", "scenarioSeries.<targetMetric>"],
    calculatedIn: "src/core/uncertainty/thermalMonteCarlo.ts → sensitivity",
    notes: [
      "В интерфейсе показывается относительная важность факторов для выбранной целевой метрики.",
      "Текущая реализация основана на корреляции и не является Morris/Sobol-анализом.",
    ],
  },
  underheatingRisk: {
    title: "Риск недогрева",
    meaning: "Вероятность того, что хотя бы в одном сценарии температура в зоне опустится ниже порога.",
    formula: "Risk = count(T_min,scenario < 20 °C) / N",
    inputs: ["minimumIndoorTemperatureC", "число сценариев N"],
    calculatedIn: "src/core/uncertainty/thermalMonteCarlo.ts → underheatingBelow20CProbability",
  },
  roomMargin: {
    title: "Запас помещения до порога",
    meaning: "Показывает, насколько P10 минимальной температуры помещения выше или ниже порогового значения 20 °C.",
    formula: "M = T_P10,min − T_lim",
    inputs: ["roomRiskSummary.minimumTemperatureP10C", "T_lim = 20 °C"],
    calculatedIn: "Results → Вероятностный анализ → производная метрика по roomRiskSummary",
  },
  cost: {
    title: "Стоимость энергии",
    meaning: "Оценка затрат на отопление при выбранном тарифе.",
    formula: "Cost = E · tariff",
    inputs: ["энергия отопления E", "тариф на тепло/электроэнергию"],
    calculatedIn: "src/core/economics/analysis.ts → runEconomicAssessment(...)",
  },
  saving: {
    title: "Экономия",
    meaning: "Разница стоимости между базовым вариантом и вариантом с мероприятием.",
    formula: "Saving = Cost_base − Cost_variant",
    inputs: ["базовая стоимость", "стоимость после мероприятия"],
    calculatedIn: "src/core/economics/analysis.ts → annualSaving_RUB",
  },
  payback: {
    title: "Окупаемость",
    meaning: "Простой срок окупаемости мероприятия или пакета мероприятий.",
    formula: "T_payback = CAPEX / annualSaving",
    inputs: ["CAPEX", "annualSaving"],
    calculatedIn: "src/core/economics/analysis.ts → calculateSimplePayback_years(...)",
  },
  npv: {
    title: "Чистый дисконтированный доход (NPV)",
    meaning: "Чистый дисконтированный доход за выбранный горизонт расчёта.",
    formula: "NPV = Σ CF_t / (1 + r)^t − CAPEX",
    inputs: ["денежный поток CF_t", "ставка дисконтирования r", "CAPEX"],
    calculatedIn: "src/core/economics/analysis.ts → calculateNpv_RUB(...)",
  },
  compactness: {
    title: "Коэффициент компактности",
    meaning: "Отношение площади наружной оболочки к отапливаемому объёму.",
    formula: "K_compact = A_env / V_h",
    calculatedIn: "src/core/thermal/derived/buildingPerformanceMetrics.ts → calculateCompactness(...)",
    notes: "Дополнительный показатель поверх RC-расчёта; не меняет основной solver.",
  },
  windowToWallRatio: {
    title: "Доля остекления фасада",
    meaning: "Отношение площади окон к площади наружных фасадов.",
    formula: "WWR = A_win / A_facade",
    calculatedIn: "src/core/thermal/derived/buildingPerformanceMetrics.ts → calculateWindowToWallRatio(...)",
    notes: "Дополнительный показатель поверх RC-расчёта.",
  },
  equivalentUValue: {
    title: "Эквивалентный U",
    meaning: "Площадно-взвешенный коэффициент теплопередачи ограждений.",
    formula: "U_eq = Σ(U_i · A_i) / ΣA_i",
    calculatedIn: "src/core/thermal/derived/buildingPerformanceMetrics.ts → calculateEquivalentUValue(...)",
  },
  heatLossTransmission: {
    title: "H_tr",
    meaning: "Трансмиссионный коэффициент теплопотерь.",
    formula: "H_tr = Σ(U_i · A_i)",
    calculatedIn: "src/core/thermal/derived/buildingPerformanceMetrics.ts",
  },
  heatLossVentilation: {
    title: "H_ve",
    meaning: "Суммарный коэффициент теплопотерь на воздухообмен (инфильтрация + вентиляция).",
    formula: "H_ve = H_inf + H_vent",
    calculatedIn: "src/core/thermal/derived/buildingPerformanceMetrics.ts",
  },
  heatLossLinearBridges: {
    title: "H_ψ",
    meaning: "Линейные тепловые мосты (явно заданные ψ·L).",
    formula: "H_ψ = Σ(ψ_i · L_i)",
    calculatedIn: "src/core/thermal/derived/buildingPerformanceMetrics.ts",
  },
  heatLossPointBridges: {
    title: "H_χ",
    meaning: "Точечные тепловые мосты (явно заданные χ).",
    formula: "H_χ = Σ(χ_i)",
    calculatedIn: "src/core/thermal/derived/buildingPerformanceMetrics.ts",
  },
  heatLossTotal: {
    title: "H_total",
    meaning: "Общий коэффициент теплопотерь здания.",
    formula: "H_total = H_tr + H_ve + H_ψ + H_χ",
    calculatedIn: "src/core/thermal/derived/buildingPerformanceMetrics.ts → calculateTotalHeatLossCoefficient(...)",
  },
  degreeHoursUnderheat: {
    title: "Градусо-часы недогрева",
    meaning: "Интеграл превышения минимальной допустимой температуры над фактической.",
    formula: "DH_underheat = Σ max(0, T_min − T_in(t)) · Δt",
    calculatedIn: "src/core/thermal/derived/buildingPerformanceMetrics.ts → calculateDegreeHoursUnderheat(...)",
    notes: "Сумма по зонам может превышать длительность сценария.",
  },
  degreeHoursOverheat: {
    title: "Градусо-часы перегрева",
    meaning: "Интеграл превышения фактической температуры над T_max.",
    formula: "DH_overheat = Σ max(0, T_in(t) − T_max) · Δt",
    calculatedIn: "src/core/thermal/derived/buildingPerformanceMetrics.ts → calculateDegreeHoursOverheat(...)",
  },
  co2Footprint: {
    title: "Углеродный след",
    meaning: "Выбросы CO₂ от потреблённой энергии.",
    formula: "CO2 = E · EF",
    calculatedIn: "src/core/thermal/derived/buildingPerformanceMetrics.ts → calculateCO2(...)",
  },
  validationMbe: {
    title: "MBE",
    meaning: "Смещение модели относительно измерений.",
    formula: "MBE = Σ(M_i − S_i) / ΣM_i · 100%",
    calculatedIn: "src/core/thermal/derived/buildingPerformanceMetrics.ts → calculateValidationMetrics(...)",
  },
  validationCvrmse: {
    title: "CVRMSE",
    meaning: "Коэффициент вариации RMSE относительно среднего измерения.",
    formula: "CVRMSE = sqrt(Σ(M_i − S_i)² / (n − 1)) / mean(M) · 100%",
    calculatedIn: "src/core/thermal/derived/buildingPerformanceMetrics.ts → calculateValidationMetrics(...)",
  },
  validationRmse: {
    title: "RMSE_T",
    meaning: "Среднеквадратичная ошибка температуры.",
    formula: "RMSE_T = sqrt(Σ(T_meas,i − T_sim,i)² / N)",
    calculatedIn: "src/core/thermal/derived/buildingPerformanceMetrics.ts → calculateValidationMetrics(...)",
  },
} satisfies Record<string, MetricInfoDefinition>;

export type ResultsMetricInfoKey = keyof typeof resultsMetricInfo;
